const word_type_short_form = {
	"noun group a": "n-a.",
	"noun group b": "n-b.",
	"noun group c": "n-c.",
	"adjective": "adj.",
	"adverb": "adv.",
	"verb": "v.",
	"conjunction": "c.",
	"phrase": "phr.",
	"onomatopeia": "on.",
	"expression": "exp.",
	"expression adverb": "expadv.",
	"interjection": "int.",
	"suffix": "suff.",
	"preposition": "pre.",
	"prefix": "pref.",
	"pronoun": "pron.",
	"auxiliary": "aux.",
	"numeral": "num."
};

const entry_words = [
	"-assi",
	"-bie",
	"-iswe",
	"-nasse",
	"-ssul",
	"ael",
	"aelassi",
	"aelfe",
	"aelu",
	"aethe",
	"aide",
	"aides",
	"ailen",
	"ailesse",
	"aimaŋ",
	"ainandie",
	"ainas",
	"ainassareni ôle",
	"aindwe",
	"aiselen",
	"aithavesh",
	"alaebai",
	"aldassil",
	"aldassilglasse",
	"alem",
	"alie",
	"alowe",
	"alte",
	"altu",
	"alûande",
	"amassa",
	"ambela",
	"anas",
	"anassor",
	"anaŋen",
	"ancir",
	"andôl",
	"ansfem",
	"ansra",
	"ansrilô",
	"ansûrvai",
	"ansûrvath",
	"antew",
	"anôsh",
	"aod",
	"aollen",
	"aoma",
	"aonash",
	"aonassi",
	"aontren",
	"aoslandie",
	"arûnashe",
	"aseresh",
	"athu",
	"aŋnen",
	"baefan",
	"baelash",
	"baiden",
	"bain",
	"baldain",
	"balwe",
	"baon",
	"basselden",
	"bassild",
	"bawilen",
	"bawilesh",
	"beizie",
	"belas",
	"beldesh",
	"beldessi",
	"beranae",
	"bere",
	"bessar",
	"bethe",
	"bew",
	"bewesh",
	"bewwiel",
	"bicil",
	"bielen",
	"bienen",
	"bilsen",
	"bim",
	"bir",
	"birima",
	"bithe",
	"biôn",
	"biôra",
	"blen",
	"blewsse",
	"blewssebie",
	"blore",
	"blôen",
	"bobewlie",
	"bollasse",
	"bollien",
	"bothen",
	"brame",
	"brelendas",
	"brien",
	"briesae",
	"briesathe",
	"brilesh",
	"briôrse",
	"bucul",
	"bwaile",
	"bwel",
	"bôr",
	"bôrand",
	"bûlwen",
	"bûlwenen",
	"bŷl",
	"cacul",
	"caemen",
	"caiben",
	"caidim",
	"caindie",
	"caindiessi",
	"cairan",
	"cairassi",
	"caissen",
	"caivas",
	"calamôr",
	"calaŋ",
	"caldash",
	"caldûi",
	"caltir",
	"calye",
	"canda",
	"cansu",
	"cantha",
	"cantir",
	"caotre",
	"carandon",
	"cassen",
	"cassil",
	"caŋ",
	"caŋnasse",
	"caŋnen",
	"caŋnentele",
	"celden",
	"celdôre",
	"celendra",
	"celene",
	"celevien",
	"celevietith",
	"celisse",
	"celondre",
	"celte",
	"cembalie",
	"cere",
	"cesh",
	"ci meltie",
	"ci",
	"cilie",
	"cinen",
	"cinûmaie",
	"cinûmaies",
	"cir",
	"cirem",
	"cirssi",
	"cithe",
	"claidwen",
	"clissa",
	"coil",
	"culden",
	"cushe",
	"cwen",
	"cwielen",
	"cwielesh",
	"côl",
	"cônde",
	"cûd",
	"cûiden",
	"cûidesh",
	"cûir",
	"cûle",
	"cûlentai",
	"cûsaŋ",
	"cûtwen",
	"cŷbas",
	"cŷlde",
	"cŷldu",
	"cŷle",
	"cŷŋ",
	"cŷŋbie",
	"cŷŋqwessie",
	"daelfa",
	"dagen",
	"dagssul",
	"dainasse",
	"dairash",
	"dalash",
	"dalashe",
	"damas",
	"damelde",
	"damwe",
	"damûr",
	"damûrssul",
	"dant",
	"dara",
	"darassil",
	"dasharen",
	"dathas",
	"dathassi",
	"daŋga",
	"delen",
	"deleŋsten",
	"denalor",
	"dewa",
	"dewwollas",
	"diel",
	"diwen",
	"dora",
	"doron",
	"doru",
	"drai",
	"draivlûrash",
	"drasse",
	"drumesh",
	"drunden",
	"drôs",
	"drûla",
	"dwaisa",
	"dwathollen",
	"dwaŋ",
	"dwaŋqwessie",
	"dwiwe",
	"dwonar",
	"dwûmassil",
	"dôranis",
	"dôre",
	"dôrse",
	"dûina",
	"dûmen",
	"dûmessi",
	"elefe",
	"elentre",
	"elessi",
	"elewwim",
	"elie",
	"emae",
	"emalûi",
	"emse",
	"emyash",
	"endecalen",
	"endûl",
	"ente",
	"entwûsa",
	"ere",
	"ereshe",
	"esash",
	"esien",
	"esûshwie",
	"ewesh",
	"ezele",
	"fa",
	"fabwe",
	"faeran",
	"faidesh",
	"faie",
	"failie",
	"failon",
	"falash",
	"falassi",
	"falye",
	"fanadai",
	"fanae",
	"fashre",
	"fashres",
	"fasse",
	"fawash",
	"fayen",
	"feile",
	"felae",
	"felde",
	"fen",
	"feres",
	"fim",
	"finden",
	"fisse",
	"flaog",
	"flecwen",
	"fliwem",
	"flont",
	"flowe",
	"flowencairassi",
	"folor",
	"fonash",
	"fonthis",
	"forona",
	"fruŋ",
	"fulde",
	"fuldu",
	"fushae",
	"futh",
	"fwagas",
	"fwashen",
	"fwaŋgent",
	"fwessiesh",
	"fûl",
	"fûr",
	"gael",
	"gai",
	"gaie",
	"gaish",
	"galash",
	"galen",
	"gaŋnesh",
	"gaŋnessi",
	"gaŋse",
	"gessesh",
	"gessil",
	"gewme",
	"glame",
	"glamialde",
	"glassan",
	"glasse",
	"glessi",
	"glessien",
	"gliefe",
	"glona",
	"glonash",
	"glorten",
	"gont",
	"goroth",
	"gulyesh",
	"gwaele",
	"gwaim",
	"gwalde",
	"gwamar",
	"gwandar",
	"gwarse",
	"gwasan",
	"gwassem",
	"gwen",
	"gwenden",
	"gwene",
	"gwentan",
	"gwer",
	"gwesen",
	"gwisse",
	"gwolor",
	"gwonde",
	"gwore",
	"gwuna",
	"gwûil",
	"gôash",
	"gôl",
	"gôllûandar",
	"gûin",
	"gûlar",
	"gûnar",
	"gŷl",
	"haeme",
	"haide",
	"haim",
	"hair",
	"haish",
	"haissen",
	"haivash",
	"haiŋ",
	"halûin",
	"hantan",
	"hasse",
	"hassu thiemen",
	"heblen",
	"hele",
	"helerôn",
	"hembûin",
	"heten",
	"hewas",
	"hiathien",
	"hicesh",
	"himai",
	"hithen",
	"hithes",
	"hiôlash",
	"hiŋgen",
	"hiŋgesh",
	"hob",
	"hube",
	"hwassi",
	"hwer",
	"hweshe",
	"hwethae",
	"hwie",
	"hwil",
	"hwir",
	"hwissa",
	"hwiôrlath",
	"hwond",
	"hwônden",
	"hŷl",
	"i",
	"ialde",
	"ian",
	"iar",
	"iare",
	"ibaiden",
	"ilare",
	"ilbu",
	"ilem",
	"indashas",
	"inde",
	"ine",
	"ine-",
	"inebeizie",
	"ineblewssebie",
	"ineindashas",
	"inende",
	"ineraeleshtil",
	"inethiemen",
	"inezile",
	"innan",
	"inyas",
	"iraidôr",
	"irithie",
	"isil",
	"ithamae",
	"ivereld",
	"jaen",
	"jaenen",
	"jaer",
	"jaethan",
	"jandre",
	"jane",
	"janûssi",
	"jelen",
	"jiôrien",
	"jow",
	"jûlen",
	"jûrwen",
	"jŷl",
	"lacen",
	"lae",
	"lagwe",
	"lande",
	"lannae",
	"lantre",
	"lanyan",
	"laog",
	"larun",
	"larunbie",
	"lassaie",
	"lemya",
	"lendessil",
	"lerie",
	"lessar",
	"lewse",
	"lewwe",
	"linde",
	"lindu cwen",
	"lindu",
	"lir",
	"lisse",
	"lissesiŋgae",
	"lith",
	"liŋgash",
	"lode",
	"lodu",
	"loias",
	"losse",
	"loth",
	"lothie",
	"luge",
	"lunas",
	"lôin",
	"lôl",
	"lômash",
	"lômen",
	"lôssen",
	"lûandar",
	"lûantir",
	"lûi",
	"lûind",
	"lûise",
	"lûl",
	"lûmassash",
	"lûnge",
	"lûngu",
	"lûr",
	"lûrbie",
	"lŷŋ",
	"maiepasvie",
	"maissen",
	"maissenassi",
	"maisses",
	"maissetele",
	"malen",
	"malentie",
	"malessi",
	"malya",
	"manaran",
	"mansiel",
	"mant",
	"mari",
	"mashe",
	"mashele",
	"masinde",
	"maslom",
	"maslos",
	"masse",
	"massil",
	"massilen",
	"mathash",
	"maŋgar",
	"maŋgwon",
	"maŋwesh",
	"maŋyalen",
	"maŋye",
	"meca",
	"meidel",
	"melanen",
	"melanssi",
	"mele",
	"melessie",
	"meltie",
	"melyabie",
	"melyan",
	"menden",
	"merassi",
	"mere",
	"mesh",
	"mi",
	"min lûl ... na",
	"min mollie ... na",
	"min",
	"mironden",
	"missi",
	"miu ôlaish",
	"miu",
	"miôren",
	"moile",
	"mollai",
	"mollie",
	"momil",
	"monae",
	"morda",
	"mrônan",
	"mrûne",
	"munas",
	"mô",
	"môlde",
	"môldehwond",
	"mône",
	"môre",
	"môril",
	"môrlas",
	"môth",
	"mûiral",
	"mûr",
	"mŷcûl",
	"mŷl",
	"naben",
	"nacen",
	"naese",
	"nagwa",
	"naiant",
	"naie",
	"nail",
	"naimash",
	"nairande",
	"naitie",
	"naitiebie",
	"nalash",
	"nan",
	"naoca",
	"naocaidim",
	"naore",
	"narash",
	"nare",
	"nashre",
	"nashres",
	"nasta",
	"naŋge",
	"naŋyash",
	"neŋ",
	"neŋtir",
	"nilzi",
	"ningse",
	"nirhala",
	"nisen",
	"nith",
	"niôŋ",
	"niŋ",
	"nobe",
	"nocor",
	"nolla",
	"nolyash",
	"nomas",
	"nossûiash",
	"nossûien",
	"nôga",
	"nôre",
	"nûen",
	"nûin",
	"nûlie",
	"nûmala",
	"nŷven",
	"ollash",
	"olorda",
	"olûre",
	"omil",
	"paed",
	"pai",
	"paiash",
	"paicen",
	"paiden",
	"paien",
	"pala",
	"panen",
	"paon",
	"paonaethe",
	"pare",
	"pase",
	"pashen",
	"pasiel",
	"path",
	"paŋ",
	"paŋge",
	"pelanôŋ",
	"pentren",
	"pessil",
	"peŋ",
	"pin",
	"pinden",
	"possai",
	"pothe",
	"pôl",
	"pôlafra",
	"pôlômash",
	"pôlômassi",
	"pônu cwen",
	"pônu",
	"pûllan",
	"pûllassi",
	"pûmar",
	"pŷŋ",
	"qwa",
	"qwael",
	"qwaelbie",
	"qwaentan",
	"qwainen",
	"qwaithe",
	"qwalan",
	"qwandae",
	"qwantash",
	"qwas",
	"qwash",
	"qwasheme",
	"qweldesh",
	"qwelyaqwessie",
	"qwelyas",
	"qwen",
	"qwerasir",
	"qwese",
	"qwessie",
	"qweth",
	"qweviel",
	"qwiresh",
	"qwiressi",
	"qwolôrna",
	"qwossan",
	"qwoŋbalas",
	"qwôl",
	"qwôlar",
	"qwôra",
	"qwôren",
	"raelesh",
	"raeleshtil",
	"raien",
	"ralwe",
	"Ranûdel",
	"rassae",
	"rassil",
	"rende",
	"ressie",
	"reŋmie",
	"rieldal",
	"rim",
	"rina",
	"rindalesh",
	"rindie",
	"roil",
	"ronathas",
	"rosse",
	"rume",
	"rumeflowe",
	"rôcand",
	"rôn",
	"rônberanae",
	"rûnas",
	"rûnathie",
	"rûndiel",
	"rŷŋ",
	"rŷŋgwandar",
	"sa (2)",
	"sa",
	"saelas",
	"saerash",
	"saerassi",
	"sailan",
	"sailas",
	"sailassi",
	"saldassi",
	"samai",
	"sanash",
	"sanaŋ",
	"sani",
	"sathas",
	"seiren",
	"seldiren",
	"selesh",
	"selo",
	"sentie",
	"serafalassi",
	"serenas",
	"serenevathas",
	"serie",
	"sesufele",
	"sevir",
	"shaelda",
	"shan",
	"sheb",
	"shelai",
	"shele",
	"shelesse",
	"shielde",
	"shone",
	"shraeŋ",
	"shrilie",
	"shrond",
	"shrunen",
	"shrŷlwe",
	"shrŷna",
	"shrŷŋ",
	"shwiŋ",
	"shôl",
	"shŷne",
	"sidir",
	"silitha",
	"silssien",
	"sin",
	"sincultir",
	"sini",
	"siten",
	"siôrash",
	"siôren",
	"siŋgae",
	"slacash",
	"slande",
	"slantha",
	"slent",
	"sloren",
	"slôssie",
	"solonde",
	"solsse",
	"sontan",
	"spacul",
	"spaid",
	"spiencelen",
	"staelfe",
	"stûinde",
	"suce",
	"swaesse",
	"swanze",
	"swind",
	"swintane",
	"swiŋye",
	"sŷlae",
	"tacwel",
	"tael",
	"taent",
	"talaraŋ",
	"taldaŋ",
	"tamalash",
	"tanten",
	"tarien",
	"tassie",
	"tayandôr",
	"taŋcan",
	"tecse",
	"telde",
	"teltan",
	"telyash",
	"tende",
	"tendessi",
	"tenild",
	"terassi",
	"tesse",
	"tessu",
	"teŋgen",
	"teŋgesh",
	"teŋnen",
	"thael",
	"thaiden",
	"thaine",
	"thaisse",
	"thalashaŋ",
	"thalassi",
	"thas",
	"thash",
	"thelen",
	"there",
	"theren",
	"theressi",
	"thewan",
	"thiemen",
	"thienas",
	"thilde",
	"thilende",
	"thilu",
	"thime",
	"thiva",
	"thobae",
	"thomash",
	"thore",
	"thrande",
	"thrûvi",
	"thrŷl",
	"thuŋ",
	"thwossiesh",
	"thûca",
	"thûcen",
	"thûrda",
	"thûvala",
	"thŷlen",
	"tilie",
	"tiren",
	"tith",
	"tiôr",
	"trew",
	"tulde",
	"twaisen",
	"twaraŋ",
	"twasa",
	"twûnesh",
	"twûssil",
	"twûssilglasse",
	"twûssilqwessie",
	"tônd",
	"tûlen",
	"tûmen",
	"tŷlai",
	"ulsela",
	"ulumai ci",
	"ulumai",
	"ulumailindu menden",
	"ulumailindu",
	"umash",
	"ussas",
	"vace",
	"vaere",
	"vai",
	"vana",
	"vancie",
	"vaondre",
	"vassash",
	"vasten",
	"vayu",
	"velie",
	"velôma",
	"veriŋnesh",
	"ves",
	"vessi",
	"viel",
	"vil",
	"vim",
	"vis",
	"visses",
	"viôrda",
	"vlenten",
	"vlussi",
	"vlûrash",
	"vonen",
	"vossae",
	"vucen",
	"vulsse",
	"vôma",
	"vônu",
	"vŷlissel",
	"waelash",
	"waelatil",
	"waelfe",
	"waide",
	"waiŋnen",
	"wamesh",
	"waren",
	"waresh",
	"wasen",
	"weles",
	"welfu",
	"wenwarie",
	"windesh",
	"windessi",
	"windeyeldie",
	"wiôlen",
	"wiôlesh",
	"wond",
	"wune",
	"wôr",
	"yaer",
	"yaeran",
	"yalssi",
	"yasen",
	"yaŋgstarssa",
	"yaŋu",
	"yeldie",
	"yelesh",
	"yelesiel",
	"yelon",
	"yendrae",
	"yene",
	"yenessi",
	"yome",
	"yune",
	"yôl",
	"yômash",
	"yûlae",
	"zaelash",
	"zaelen",
	"zaer",
	"zaerai",
	"zaesh",
	"zaeshe",
	"zaevai",
	"zaias",
	"zaimse",
	"zaitash",
	"zaiwen",
	"zalûdiem",
	"zane",
	"zanse",
	"zaranil",
	"zasha",
	"zath",
	"zathbie",
	"zeile",
	"zelesh",
	"zemiel",
	"zenesh",
	"zenessi",
	"zerûla",
	"zerûlafelde",
	"zesûind",
	"ziena",
	"zilen",
	"zirfai",
	"zisses",
	"zlaemash",
	"zlonden",
	"zlondessi",
	"zlondiswe",
	"zolla",
	"zonde",
	"zrônel",
	"zôlsil",
	"zôril",
	"zûinu",
	"zûlas",
	"zûren",
	"zŷl",
	"ôb",
	"ôces",
	"ôlaish",
	"ôlathvial",
	"ôldaissa",
	"ôldassi",
	"ôle",
	"ôlir",
	"ôlse",
	"ôrbin",
	"ôrshen",
	"ôrshenassi",
	"ôrshes",
	"ôrshetele",
	"ôsa",
	"ôte",
	"ûcanan",
	"ûcanash",
	"ûga",
	"ûllanor",
	"ûne yaeran",
	"ûne",
	"ûrci",
	"ûthe",
	"ŷcil",
	"ŷre",
	"ŷrŋ",
];

const entries = {
	"-assi": ["suffix", "non-noun to noun suffix; gerund; nominalisation suffix"],
	"-bie": ["adjective", "-like, -ly (forms adjectives)"],
	"-iswe": ["suffix", "-ness (attached to adjectives or verbs) (noun group a)"],
	"-nasse": ["suffix", "agent/worker suffix"],
	"-ssul": ["suffix", "non-noun to noun suffix; gerund; nominalisation suffix (noun group c form)"],
	"ael": ["preposition", "out"],
	"aelassi": ["noun group a", "outside"],
	"aelfe": ["noun group a", "alfur (norse myth elves)"],
	"aelu": ["adverb", "out of"],
	"aethe": ["noun group a", "day"],
	"aide": ["noun group a", "nobility"],
	"aides": ["adjective", "noble"],
	"ailen": ["adverb", "early"],
	"ailesse": ["noun group a", "mountain peak"],
	"aimaŋ": ["noun group a", "ivy"],
	"ainandie": ["noun group a", "rite, ritual"],
	"ainas": ["adjective", "sacred, holy"],
	"ainassareni ôle": ["phrase", "a greeting"],
	"aindwe": ["noun group a", "happiness, bliss"],
	"aiselen": ["verb", "to bless"],
	"aithavesh": ["verb", "to be aware, to be cautious, to beware"],
	"alaebai": ["noun group a", "sun shafts"],
	"aldassil": ["noun group a", "sun"],
	"aldassilglasse": ["noun group a", "sunlight"],
	"alem": ["noun group a", "memory"],
	"alie": ["noun group a", "color, colour"],
	"alowe": ["noun group a", "kid, child"],
	"alte": ["noun group a", "top"],
	"altu": ["preposition", "over, above"],
	"alûande": ["noun group a", "ocean"],
	"amassa": ["noun group c", "monster"],
	"ambela": ["noun group b", "quiver"],
	"anas": ["adjective", "any, anything"],
	"anassor": ["adjective", "rich, wealthy"],
	"anaŋen": ["verb", "to bite"],
	"ancir": ["noun group b", "army"],
	"andôl": ["noun group c", "enemy"],
	"ansfem": ["noun group a", "sister"],
	"ansra": ["conjunction", "how"],
	"ansrilô": ["conjunction", "what"],
	"ansûrvai": ["conjunction", "why"],
	"ansûrvath": ["conjunction", "where"],
	"antew": ["noun group b", "table"],
	"anôsh": ["verb", "to go, to move"],
	"aod": ["numeral", "too many, too much"],
	"aollen": ["adverb", "after"],
	"aoma": ["numeral", "eight"],
	"aonash": ["verb", "to sing"],
	"aonassi": ["noun group a", "song, singing"],
	"aontren": ["verb", "to follow"],
	"aoslandie": ["noun group a", "culture"],
	"arûnashe": ["noun group a", "religion"],
	"aseresh": ["verb", "vanish"],
	"athu": ["adverb", "up, upwards"],
	"aŋnen": ["verb", "to put, to place, to move something to a place"],
	"baefan": ["numeral", "thousand"],
	"baelash": ["verb", "to blush from embarrassment"],
	"baiden": ["verb", "to ask"],
	"bain": ["adverb", "instantly, suddenly"],
	"baldain": ["noun group b", "baldric"],
	"balwe": ["noun group a", "cream"],
	"baon": ["noun group b", "payment, tribute"],
	"basselden": ["verb", "to curse"],
	"bassild": ["noun group c", "curse"],
	"bawilen": ["verb", "to deteriorate, to disintegrate, to break down"],
	"bawilesh": ["noun group a", "to dissipate, to disintegrate, to turn into nothing"],
	"beizie": ["noun group a", "people, folk"],
	"belas": ["adjective", "other, another"],
	"beldesh": ["verb", "to dance"],
	"beldessi": ["noun group a", "dance"],
	"beranae": ["noun group a", "family"],
	"bere": ["pronoun", "they, them"],
	"bessar": ["adjective", "warm"],
	"bethe": ["noun group a", "big cat"],
	"bew": ["noun group a", "lip"],
	"bewesh": ["verb", "to play, to entertain oneself"],
	"bewwiel": ["noun group a", "foreigner, stranger"],
	"bicil": ["noun group c", "garbage"],
	"bielen": ["verb", "to give, to grant"],
	"bienen": ["verb", "to send"],
	"bilsen": ["verb", "to guide"],
	"bim": ["noun group a", "boy"],
	"bir": ["pronoun", "he, him"],
	"birima": ["noun group b", "farm, plantation"],
	"bithe": ["noun group a", "man, male"],
	"biôn": ["noun group b", "lesson"],
	"biôra": ["noun group b", "inn, hotel"],
	"blen": ["verb", "to touch, to feel something physical"],
	"blewsse": ["noun group a", "comfort"],
	"blewssebie": ["adjective", "comfortable"],
	"blore": ["noun group a", "wool"],
	"blôen": ["verb", "to feel an emotion; to feel pain"],
	"bobewlie": ["noun group a", "potato"],
	"bollasse": ["noun group a", "wood"],
	"bollien": ["noun group b", "vase"],
	"bothen": ["verb", "to destroy, to break"],
	"brame": ["noun group a", "carrot"],
	"brelendas": ["adjective", "complex, intricate"],
	"brien": ["adverb", "before"],
	"briesae": ["noun group a", "experience, memory"],
	"briesathe": ["noun group a", "yesterday"],
	"brilesh": ["verb", "to rest, to take a break"],
	"briôrse": ["noun group a", "wasp"],
	"bucul": ["noun group c", "skull"],
	"bwaile": ["noun group a", "deer"],
	"bwel": ["noun group c", "poison"],
	"bôr": ["noun group a", "swamp, bog"],
	"bôrand": ["noun group b", "letter (a message)"],
	"bûlwen": ["noun group b", "shield"],
	"bûlwenen": ["verb", "to shield, to protect"],
	"bŷl": ["noun group a", "sprout, shoot of plant"],
	"cacul": ["noun group c", "troll"],
	"caemen": ["verb", "to seem like"],
	"caiben": ["verb", "to wound"],
	"caidim": ["noun group b", "axe (weapon)"],
	"caindie": ["noun group a", "allegiance, fidelity"],
	"caindiessi": ["noun group a", "alliance"],
	"cairan": ["verb", "to crack, to split"],
	"cairassi": ["noun group a", "crack (thin opening or damage on a hard surface)"],
	"caissen": ["verb", "to grind, to crush"],
	"caivas": ["noun group b", "mace (weapon)"],
	"calamôr": ["noun group a", "world, universe"],
	"calaŋ": ["noun group b", "cup, mug, tankard, goblet"],
	"caldash": ["verb", "to appear"],
	"caldûi": ["noun group a", "twilight"],
	"caltir": ["noun group a", "cabbage, lettuce"],
	"calye": ["noun group a", "bay"],
	"canda": ["noun group b", "helmet"],
	"cansu": ["adverb", "eastward"],
	"cantha": ["noun group b", "cloth, fabric"],
	"cantir": ["noun group a", "block, cube, brick"],
	"caotre": ["noun group a", "east"],
	"carandon": ["noun group a", "tower karst, extremely jagged mountain"],
	"cassen": ["verb", "to carve"],
	"cassil": ["noun group a", "dust, powder"],
	"caŋ": ["noun group a", "arcane spell"],
	"caŋnasse": ["noun group a", "wizard"],
	"caŋnen": ["verb", "to bend, to twist"],
	"caŋnentele": ["adjective", "bent, twisted, crooked"],
	"celden": ["verb", "to grasp, to grab, to manhandle, to hold forcefully"],
	"celdôre": ["noun group a", "makeup, perfume, body care product, cream"],
	"celendra": ["noun group b", "crown, circlet"],
	"celene": ["adjective", "safe, secure"],
	"celevien": ["verb", "to watch"],
	"celevietith": ["noun group b", "watchtower"],
	"celisse": ["noun group a", "horse"],
	"celondre": ["noun group b", "glass"],
	"celte": ["noun group a", "meat, flesh"],
	"cembalie": ["noun group a", "meeting, gathering, assemblage, assembly (archaically called a thing)"],
	"cere": ["noun group a", "health"],
	"cesh": ["verb", "to jump, to hop"],
	"ci meltie": ["conjunction", "while, whilst"],
	"ci": ["preposition", "towards, to, at"],
	"cilie": ["adjective/adverb", "perfect, perfectly"],
	"cinen": ["verb", "to dig"],
	"cinûmaie": ["noun group a", "royality"],
	"cinûmaies": ["adjective", "royal"],
	"cir": ["adjective", "new"],
	"cirem": ["noun group b", "sword (weapon)"],
	"cirssi": ["noun group a", "news, tidings"],
	"cithe": ["noun group a", "ear"],
	"claidwen": ["verb", "to summon, to call upon, to call for"],
	"clissa": ["noun group b", "saddle"],
	"coil": ["noun group c", "death"],
	"culden": ["verb", "to build"],
	"cushe": ["noun group a", "nut"],
	"cwen": ["verb", "to see, to look at"],
	"cwielen": ["verb", "to freeze"],
	"cwielesh": ["verb", "to become frozen, to freeze"],
	"côl": ["adverb", "no"],
	"cônde": ["noun group a", "teeth, fang"],
	"cûd": ["noun group c", "skeleton"],
	"cûiden": ["verb", "to wake someone/something up"],
	"cûidesh": ["verb", "to wake up, to become awake, to awaken"],
	"cûir": ["noun group a", "sight, view"],
	"cûle": ["adjective", "alone"],
	"cûlentai": ["noun group a", "the eternal mist; the ethereal blue mist that surrounds the mountains of ranudel"],
	"cûsaŋ": ["noun group a", "vine"],
	"cûtwen": ["noun group b", "toilet"],
	"cŷbas": ["adjective", "thirsty"],
	"cŷlde": ["noun group a", "west"],
	"cŷldu": ["adverb", "westward"],
	"cŷle": ["noun group a", "a fog pool formed in the ground when the morning fog dissipates"],
	"cŷŋ": ["noun group a", "cold"],
	"cŷŋbie": ["adjective", "cold"],
	"cŷŋqwessie": ["noun group a", "cold elf"],
	"daelfa": ["numeral", "four"],
	"dagen": ["verb", "to kill, to slay, to murder"],
	"dagssul": ["noun group c", "murder"],
	"dainasse": ["noun group a", "cut crystal, cut gem"],
	"dairash": ["verb", "to hurry, to make haste"],
	"dalash": ["verb", "to redden"],
	"dalashe": ["noun group a", "crystal, gem"],
	"damas": ["adjective", "red"],
	"damelde": ["noun group a", "language"],
	"damwe": ["noun group a", "darkness, gloom, murk, shadow"],
	"damûr": ["adjective", "dark, dim"],
	"damûrssul": ["noun group c", "darkness, shadow; a dark hiding spot"],
	"dant": ["noun group b", "staff, stave"],
	"dara": ["noun group b", "copper"],
	"darassil": ["noun group a", "glade, forest clearing"],
	"dasharen": ["verb", "to startle, to frighten, to scare, to shock (fleeting scare)"],
	"dathas": ["adjective", "hard to break, sturdy"],
	"dathassi": ["noun group b", "locking mechanicism, padlock, lock system"],
	"daŋga": ["noun group b", "ore"],
	"delen": ["verb", "to hold"],
	"deleŋsten": ["verb", "to experience, to feel"],
	"denalor": ["noun group c", "oblivion, devastation"],
	"dewa": ["noun group b", "quill, pen"],
	"dewwollas": ["adjective", "lush"],
	"diel": ["noun group a", "fish"],
	"diwen": ["verb", "to need, to require"],
	"dora": ["noun group b", "clan, tribe"],
	"doron": ["noun group b", "castle, fortress"],
	"doru": ["adverb", "only (count)"],
	"drai": ["noun group c", "blood"],
	"draivlûrash": ["verb", "to bleed"],
	"drasse": ["noun group a", "story, tale"],
	"drumesh": ["verb", "to hum"],
	"drunden": ["verb", "to ride"],
	"drôs": ["adjective", "blue"],
	"drûla": ["noun group b", "arrow (weapon)"],
	"dwaisa": ["noun group b", "brass"],
	"dwathollen": ["verb", "to control, to manipulate, to rule over"],
	"dwaŋ": ["noun group a", "night"],
	"dwaŋqwessie": ["noun group a", "night elf (world of warcraft)"],
	"dwiwe": ["noun group a", "beam of light or magic"],
	"dwonar": ["adjective", "dangerous"],
	"dwûmassil": ["noun group a", "field"],
	"dôranis": ["noun group b", "message"],
	"dôre": ["article", "question article (questions that don't start with a conjunction start with a question article)"],
	"dôrse": ["noun group a", "penis"],
	"dûina": ["noun group b", "bronze"],
	"dûmen": ["verb", "to count"],
	"dûmessi": ["noun group a", "count, amount; number"],
	"elefe": ["noun group a", "floor, ground (built)"],
	"elentre": ["noun group a", "elm"],
	"elessi": ["noun group a", "vegetable"],
	"elewwim": ["noun group a", "medicine"],
	"elie": ["noun group a", "will, willpower, spirit"],
	"emae": ["noun group a", "spirit, soul"],
	"emalûi": ["noun group a", "a giant, enourmous river"],
	"emse": ["noun group a", "(anthropology) face"],
	"emyash": ["verb", "to gleam, to glow"],
	"endecalen": ["verb", "to surround; to flank"],
	"endûl": ["noun group b", "gate"],
	"ente": ["adjective", "common"],
	"entwûsa": ["noun group c", "war"],
	"ere": ["pronoun", "i, me"],
	"ereshe": ["noun group a", "plant"],
	"esash": ["verb", "to speak, to talk"],
	"esien": ["verb", "to say"],
	"esûshwie": ["noun group a", "herb"],
	"ewesh": ["verb", "to cry silently, to weep, to tear up"],
	"ezele": ["adjective", "green"],
	"fa": ["preposition", "at a place"],
	"fabwe": ["noun group a", "berry"],
	"faeran": ["verb", "to share"],
	"faidesh": ["verb", "to suppose, to assume"],
	"faie": ["adverb", "there"],
	"failie": ["noun group a", "fey, fae, fairy, faerie"],
	"failon": ["noun group b", "feast, banquet"],
	"falash": ["verb", "to fly"],
	"falassi": ["noun group a", "flight"],
	"falye": ["noun group a", "sea"],
	"fanadai": ["noun group a", "awe, terror"],
	"fanae": ["noun group a", "art"],
	"fashre": ["noun group a", "respect, obedience"],
	"fashres": ["adjective", "respectful"],
	"fasse": ["article", "those"],
	"fawash": ["verb", "to blow"],
	"fayen": ["verb", "to smell, to sniff"],
	"feile": ["noun group a", "fur"],
	"felae": ["noun group a", "trait, attribute, property"],
	"felde": ["noun group a", "road, trail, path, street"],
	"fen": ["verb", "to try, to attempt"],
	"feres": ["adjective", "friendly, good-mannered, nice"],
	"fim": ["noun group a", "hair"],
	"finden": ["verb", "to put on, to wear"],
	"fisse": ["article", "these"],
	"flaog": ["noun group c", "internal organ"],
	"flecwen": ["verb", "to roast"],
	"fliwem": ["noun group a", "realm, world, land, area; place, location"],
	"flont": ["noun group b", "cart, wagon"],
	"flowe": ["noun group a", "land, ground"],
	"flowencairassi": ["noun group a", "crevasse"],
	"folor": ["adjective", "poor"],
	"fonash": ["verb", "to lay down"],
	"fonthis": ["adjective", "large, big"],
	"forona": ["noun group b", "soldier"],
	"fruŋ": ["noun group b", "prison cell"],
	"fulde": ["noun group a", "north"],
	"fuldu": ["adverb", "northward"],
	"fushae": ["noun group a", "bush, tall grass"],
	"futh": ["noun group c", "demon, devil"],
	"fwagas": ["adjective", "disgusting, gross"],
	"fwashen": ["verb", "to forge, to smith; to make with metal"],
	"fwaŋgent": ["noun group b", "anvil"],
	"fwessiesh": ["verb", "to pray"],
	"fûl": ["noun group c", "evil"],
	"fûr": ["preposition", "off"],
	"gael": ["noun group a", "egg"],
	"gai": ["preposition", "on"],
	"gaie": ["noun group a", "elk"],
	"gaish": ["verb", "to dare"],
	"galash": ["verb", "to gallop"],
	"galen": ["verb", "to hate"],
	"gaŋnesh": ["verb", "to chant, to speak an incantation"],
	"gaŋnessi": ["noun group a", "chant, incantation"],
	"gaŋse": ["noun group a", "drum"],
	"gessesh": ["verb", "to breathe"],
	"gessil": ["noun group b", "room"],
	"gewme": ["noun group a", "fog"],
	"glame": ["noun group a", "king"],
	"glamialde": ["noun group a", "prince"],
	"glassan": ["verb", "to listen"],
	"glasse": ["noun group a", "light"],
	"glessi": ["noun group a", "knot"],
	"glessien": ["verb", "to tie a knot"],
	"gliefe": ["noun group a", "scale (of a reptile or fish)"],
	"glona": ["noun group b", "seat"],
	"glonash": ["verb", "to sit down"],
	"glorten": ["verb", "to hurt, to cause pain to"],
	"gont": ["noun group c", "trap"],
	"goroth": ["noun group c", "horror, abomination, atrocity"],
	"gulyesh": ["verb", "to melt"],
	"gwaele": ["noun group a", "queen"],
	"gwaim": ["noun group a", "sound, noise"],
	"gwalde": ["adjective", "old, aged"],
	"gwamar": ["adjective", "bad"],
	"gwandar": ["noun group a", "magic"],
	"gwarse": ["noun group a", "hornet"],
	"gwasan": ["verb", "to exercise, to work out"],
	"gwassem": ["noun group b", "a mineshaft"],
	"gwen": ["pronoun", "you"],
	"gwenden": ["verb", "to craft, to create, to make"],
	"gwene": ["noun group a", "shadow"],
	"gwentan": ["verb", "to write"],
	"gwer": ["adjective", "stupid"],
	"gwesen": ["verb", "to kiss, to peck"],
	"gwisse": ["noun group a", "second (a unit of time)"],
	"gwolor": ["noun group b", "anger"],
	"gwonde": ["noun group a", "ravine, canyon, gorge"],
	"gwore": ["noun group a", "mouth"],
	"gwuna": ["noun group b", "currency, money"],
	"gwûil": ["noun group a", "choir"],
	"gôash": ["verb", "to rot, to decay"],
	"gôl": ["noun group b", "fire torch"],
	"gôllûandar": ["noun group b", "fire steel, fire striker"],
	"gûin": ["noun group a", "a soft, ethereal light"],
	"gûlar": ["adjective", "low, short"],
	"gûnar": ["adjective", "barbaric, ungraceful, crude"],
	"gŷl": ["noun group a", "year"],
	"haeme": ["noun group a", "human"],
	"haide": ["noun group a", "flow, stream, run; way, path"],
	"haim": ["noun group a", "gender"],
	"hair": ["adjective/adverb", "loud"],
	"haish": ["noun group b", "hauberk"],
	"haissen": ["verb", "to hug, to embrace"],
	"haivash": ["verb", "to rise"],
	"haiŋ": ["noun group a", "storm"],
	"halûin": ["noun group c", "dragon, wyrm"],
	"hantan": ["verb", "to throw, to lob, to chuck"],
	"hasse": ["noun group a", "hand"],
	"hassu thiemen": ["verb", "to hold someone's hand, to lead someone by hand"],
	"heblen": ["verb", "to keep"],
	"hele": ["noun group a", "fire"],
	"helerôn": ["noun group a", "volcano"],
	"hembûin": ["noun group a", "salmon"],
	"heten": ["noun group b", "cubit"],
	"hewas": ["adjective", "brown"],
	"hiathien": ["verb", "to provoke, to aggravate, to anger"],
	"hicesh": ["verb", "to skip around, to frolick merrily"],
	"himai": ["noun group b", "shirt, tunic"],
	"hithen": ["verb", "to anger"],
	"hithes": ["adjective", "angry"],
	"hiôlash": ["verb", "to jump, to leap"],
	"hiŋgen": ["verb", "to train, to teach"],
	"hiŋgesh": ["verb", "to practice, to train"],
	"hob": ["noun group c", "goblin"],
	"hube": ["noun group a", "nose"],
	"hwassi": ["noun group a", "hour"],
	"hwer": ["adjective/adverb", "fast, quick"],
	"hweshe": ["noun group a", "sand"],
	"hwethae": ["noun group a", "list, collection"],
	"hwie": ["noun group a", "sweat"],
	"hwil": ["noun group a", "time"],
	"hwir": ["adjective", "simple"],
	"hwissa": ["numeral", "seven"],
	"hwiôrlath": ["noun group b", "school, academy"],
	"hwond": ["noun group b", "guard, guardsman, patroller, watchman"],
	"hwônden": ["verb", "to soak, to drench"],
	"hŷl": ["noun group a", "forest heather"],
	"i": ["article", "substitute article for the subject case"],
	"ialde": ["noun group a", "son"],
	"ian": ["noun group b", "bridge"],
	"iar": ["adjective", "hot"],
	"iare": ["noun group a", "heat"],
	"ibaiden": ["verb", "to answer"],
	"ilare": ["noun group a", "sky"],
	"ilbu": ["adverb", "down, downwards"],
	"ilem": ["noun group a", "ink"],
	"indashas": ["adjective/adverb", "possible"],
	"inde": ["verb", "to do, to act (no infinitive)"],
	"ine": ["numeral", "zero"],
	"ine-": ["prefix", "negator prefix"],
	"inebeizie": ["noun group a", "no one"],
	"ineblewssebie": ["adjective", "uncomfortable"],
	"ineindashas": ["adjective/adverb", "impossible"],
	"inende": ["verb", "to do not"],
	"ineraeleshtil": ["adjective", "eternal, forever, undying"],
	"inethiemen": ["verb", "to mislead"],
	"inezile": ["noun group b", "wall"],
	"innan": ["verb", "to not be"],
	"inyas": ["adjective", "small, little"],
	"iraidôr": ["noun group a", "ruby"],
	"irithie": ["noun group a", "silver"],
	"isil": ["noun group a", "eye"],
	"ithamae": ["verb", "painting"],
	"ivereld": ["noun group b", "mission, quest"],
	"jaen": ["noun group b", "stairs"],
	"jaenen": ["verb", "to heal a wound"],
	"jaer": ["noun group b", "door"],
	"jaethan": ["verb", "to paint"],
	"jandre": ["noun group a", "a poetic, flowing song; a ballad"],
	"jane": ["noun group a", "jade"],
	"janûssi": ["noun group a", "disease, sickness, illness"],
	"jelen": ["adverb", "late"],
	"jiôrien": ["noun group b", "scroll"],
	"jow": ["noun group b", "group, party, company"],
	"jûlen": ["verb", "to eat"],
	"jûrwen": ["noun group b", "ship"],
	"jŷl": ["noun group a", "dew"],
	"lacen": ["verb", "to scare, to frighten"],
	"lae": ["pronoun", "she, her"],
	"lagwe": ["noun group a", "oil"],
	"lande": ["adjective", "empty"],
	"lannae": ["noun group a", "woman"],
	"lantre": ["noun group a", "lake"],
	"lanyan": ["verb", "to weave"],
	"laog": ["noun group c", "tar, pitch"],
	"larun": ["noun group b", "desert, desolate land"],
	"larunbie": ["adjective", "desolate, deserted, completely empty"],
	"lassaie": ["noun group a", "allure, appeal, attractiveness"],
	"lemya": ["noun group a", "smell, aroma, fragrance"],
	"lendessil": ["noun group a", "grove"],
	"lerie": ["noun group a", "lyre"],
	"lessar": ["adjective", "absentminded, thoughtless, unwise; ambitionless, unfocused, wandering"],
	"lewse": ["noun group a", "fat, grease"],
	"lewwe": ["noun group a", "smell, odor, aroma"],
	"linde": ["noun group a", "back"],
	"lindu cwen": ["verb", "to put away"],
	"lindu": ["adverb", "backwards"],
	"lir": ["adverb", "but, yet, still"],
	"lisse": ["noun group a", "water"],
	"lissesiŋgae": ["noun group a", "saltwater brine"],
	"lith": ["noun group b", "dust, grime"],
	"liŋgash": ["verb", "to trail, to leave a trail"],
	"lode": ["noun group a", "left"],
	"lodu": ["adverb", "leftwards"],
	"loias": ["adjective", "pink"],
	"losse": ["noun group a", "snow"],
	"loth": ["noun group b", "bread"],
	"lothie": ["noun group a", "temple, shrine, religious place"],
	"luge": ["noun group a", "mud, ooze"],
	"lunas": ["adjective", "mild, gentle, kind, nice, friendly, sweet"],
	"lôin": ["adverb", "now"],
	"lôl": ["noun group a", "hill"],
	"lômash": ["verb", "to learn"],
	"lômen": ["verb", "to teach"],
	"lôssen": ["verb", "to beg, to plead"],
	"lûandar": ["noun group b", "steel"],
	"lûantir": ["noun group b", "crossbow (weapon)"],
	"lûi": ["noun group a", "river"],
	"lûind": ["noun group b", "village, town, settlement"],
	"lûise": ["noun group a", "month"],
	"lûl": ["noun group a", "life"],
	"lûmassash": ["verb", "to cry, to weep"],
	"lûnge": ["noun group a", "bottom"],
	"lûngu": ["preposition", "under"],
	"lûr": ["adjective/adverb", "slow, slowly"],
	"lûrbie": ["adjective/adverb", "lazy"],
	"lŷŋ": ["noun group a", "willow"],
	"maiepasvie": ["noun group b", "cathedral"],
	"maissen": ["verb", "to cheer up"],
	"maissenassi": ["noun group a", "happiness, joy, glee"],
	"maisses": ["adjective", "happy, joyful, gleeful"],
	"maissetele": ["adjective", "happy, joyful, gleeful (because of something); proud"],
	"malen": ["verb", "to mix, to blend, to stir"],
	"malentie": ["noun group a", "blue poppy (flower)"],
	"malessi": ["noun group a", "mix, blend, concoction; chaotic group, melting pot of things; compilation"],
	"malya": ["noun group b", "government"],
	"manaran": ["verb", "to escape, to flee"],
	"mansiel": ["noun group a", "diamond"],
	"mant": ["noun group c", "trouble, problem"],
	"mari": ["noun group a", "letter, rune"],
	"mashe": ["noun group a", "food"],
	"mashele": ["noun group a", "meal"],
	"masinde": ["noun group a", "result, conclusion, fate, destiny"],
	"maslom": ["noun group a", "ball, sphere"],
	"maslos": ["adjective", "orange (color)"],
	"masse": ["noun group a", "bird"],
	"massil": ["noun group a", "name"],
	"massilen": ["verb", "to name, to call"],
	"mathash": ["verb", "to work, to labour"],
	"maŋgar": ["adjective", "brave, bold, courageous"],
	"maŋgwon": ["noun group c", "smell, stench"],
	"maŋwesh": ["verb", "to stink, to emit a bad smell, to emit a stench"],
	"maŋyalen": ["verb", "to invoke, to provoke, to rouse, to stir"],
	"maŋye": ["noun group a", "potion, concoction, mixture"],
	"meca": ["noun group b", "brick"],
	"meidel": ["noun group b", "shovel"],
	"melanen": ["verb", "to help"],
	"melanssi": ["noun group a", "help, assistance"],
	"mele": ["adjective", "melodic, lyrical"],
	"melessie": ["noun group a", "poem"],
	"meltie": ["conjunction", "when"],
	"melyabie": ["adjective", "lovely, adorable"],
	"melyan": ["verb", "to love"],
	"menden": ["verb", "to pay"],
	"merassi": ["noun group a", "friend"],
	"mere": ["noun group b", "favourite"],
	"mesh": ["verb", "to can, to be able to"],
	"mi": ["preposition", "in, inside"],
	"min lûl ... na": ["adjective", "alive"],
	"min mollie ... na": ["adjective", "busy"],
	"min": ["adverb", "by, beside, with; of"],
	"mironden": ["verb", "to infect"],
	"missi": ["noun group a", "inside"],
	"miu ôlaish": ["verb", "to fall asleep"],
	"miu": ["adverb", "into"],
	"miôren": ["verb", "to care for, to nurture"],
	"moile": ["noun group a", "hole"],
	"mollai": ["adverb", "more"],
	"mollie": ["noun group a", "work, labour, job"],
	"momil": ["noun group a", "owl"],
	"monae": ["noun group a", "body, torso"],
	"morda": ["noun group b", "map"],
	"mrônan": ["verb", "to kiss passionately"],
	"mrûne": ["adjective", "hungry"],
	"munas": ["adjective", "sleepy, tired, drowsy"],
	"mô": ["conjunction", "or"],
	"môlde": ["noun group b", "battle"],
	"môldehwond": ["noun group b", "warrior"],
	"mône": ["adjective", "smart, intelligent"],
	"môre": ["noun group a", "fox"],
	"môril": ["noun group b", "bowl"],
	"môrlas": ["adjective", "wrong"],
	"môth": ["noun group c", "wraith"],
	"mûiral": ["noun group b", "armor, armour"],
	"mûr": ["noun group b", "basin, sink"],
	"mŷcûl": ["noun group c", "witch, hag"],
	"mŷl": ["noun group a", "gull, seagull"],
	"naben": ["verb", "to take, to get"],
	"nacen": ["verb", "to chop, to slice"],
	"naese": ["noun group a", "leg"],
	"nagwa": ["noun group a", "scar"],
	"naiant": ["noun group b", "land, plain, moor; a wide land with little to no trees"],
	"naie": ["adverb", "here"],
	"nail": ["noun group a", "piece, part"],
	"naimash": ["verb", "to worry"],
	"nairande": ["noun group a", "ghost pipe (flower)"],
	"naitie": ["noun group a", "truth"],
	"naitiebie": ["adjective/adverb", "true, right, correct"],
	"nalash": ["verb", "to walk"],
	"nan": ["verb", "to be (verb group b)"],
	"naoca": ["noun group b", "rock, stone"],
	"naocaidim": ["noun group b", "pickaxe"],
	"naore": ["noun group a", "rose (flower)"],
	"narash": ["verb", "to resist, to withstand, to endure, to bear (with or without \"vai\")"],
	"nare": ["noun group a", "dog, hound"],
	"nashre": ["noun group a", "grace, elegancy"],
	"nashres": ["adjective", "graceful, elegant"],
	"nasta": ["noun group b", "belt"],
	"naŋge": ["noun group a", "orange (food)"],
	"naŋyash": ["verb", "to shine, to gleam"],
	"neŋ": ["noun group a", "valley, mountain gorge"],
	"neŋtir": ["noun group b", "spellbook, tome, grimoire"],
	"nilzi": ["noun group c", "a scar caused by malice"],
	"ningse": ["noun group a", "goat"],
	"nirhala": ["noun group b", "whip"],
	"nisen": ["verb", "to tell someone, to say to someone"],
	"nith": ["noun group c", "a chilly ot unnerving feeling"],
	"niôŋ": ["noun group a", "bee"],
	"niŋ": ["conjunction", "and"],
	"nobe": ["adjective", "half"],
	"nocor": ["noun group b", "lava, magma"],
	"nolla": ["noun group b", "urn"],
	"nolyash": ["verb", "to wish"],
	"nomas": ["noun group b", "boat"],
	"nossûiash": ["verb", "to come together, to gather up, to group together"],
	"nossûien": ["verb", "to gather, to collect"],
	"nôga": ["noun group c", "corpse, dead body"],
	"nôre": ["noun group a", "front"],
	"nûen": ["verb", "to make"],
	"nûin": ["noun group a", "pond"],
	"nûlie": ["noun group a", "flower petal"],
	"nûmala": ["noun group b", "library"],
	"nŷven": ["noun group b", "to chew"],
	"ollash": ["verb", "to relax"],
	"olorda": ["noun group b", "fight, brawl, struggle"],
	"olûre": ["noun group a", "voice"],
	"omil": ["noun group a", "mushroom, toadstood, fungus"],
	"paed": ["noun group b", "word"],
	"pai": ["numeral", "two"],
	"paiash": ["verb", "to stop, to halt"],
	"paicen": ["adverb", "never"],
	"paiden": ["verb", "to shoot (with or without \"ci\")"],
	"paien": ["verb", "to stop something/someone; to block something"],
	"pala": ["noun group b", "trumpet"],
	"panen": ["verb", "to have"],
	"paon": ["adverb", "next"],
	"paonaethe": ["noun group a", "tomorrow"],
	"pare": ["adjective/adverb", "rare, rarely"],
	"pase": ["noun group a", "cat"],
	"pashen": ["verb", "to cut, to slash"],
	"pasiel": ["noun group a", "father"],
	"path": ["noun group b", "plate"],
	"paŋ": ["noun group b", "bow (weapon)"],
	"paŋge": ["noun group a", "clay"],
	"pelanôŋ": ["noun group b", "wine"],
	"pentren": ["verb", "to trespass, to walk into forbidden land"],
	"pessil": ["noun group a", "skin"],
	"peŋ": ["noun group b", "tavern, restaurant"],
	"pin": ["noun group b", "insult"],
	"pinden": ["verb", "to taunt, to provoke; to mock"],
	"possai": ["adverb", "many, much, a lot"],
	"pothe": ["noun group a", "head (anatomy)"],
	"pôl": ["noun group b", "symbol, glyph"],
	"pôlafra": ["noun group b", "book"],
	"pôlômash": ["verb", "to explode"],
	"pôlômassi": ["noun group a", "explosion"],
	"pônu cwen": ["verb", "to take out, to bring out"],
	"pônu": ["adverb", "forwards"],
	"pûllan": ["verb", "to test, to assess, to proof"],
	"pûllassi": ["noun group a", "test, examination, assessment"],
	"pûmar": ["adjective", "rude, mean, impolite"],
	"pŷŋ": ["noun group a", "sprig, branchlet"],
	"qwa": ["noun group b", "coin"],
	"qwael": ["noun group a", "cave, cavern"],
	"qwaelbie": ["adjective", "undergound"],
	"qwaentan": ["verb", "to abandon"],
	"qwainen": ["verb", "to cure a sickness"],
	"qwaithe": ["noun group a", "hide (animal skin)"],
	"qwalan": ["verb", "to read"],
	"qwandae": ["noun group a", "fruit"],
	"qwantash": ["verb", "to run, to sprint"],
	"qwas": ["adjective", "purple"],
	"qwash": ["noun group b", "stew"],
	"qwasheme": ["noun group a", "pumpkin"],
	"qweldesh": ["verb", "to hide"],
	"qwelyaqwessie": ["noun group a", "high elf (d&d)"],
	"qwelyas": ["adjective", "great, magnificent"],
	"qwen": ["noun group b", "gold"],
	"qwerasir": ["noun group b", "kingdom, empire, nation"],
	"qwese": ["noun group a", "small river, stream"],
	"qwessie": ["noun group a", "elf"],
	"qweth": ["noun group b", "soup"],
	"qweviel": ["noun group a", "thoughts, mind"],
	"qwiresh": ["verb", "to rain"],
	"qwiressi": ["noun group a", "rainfall"],
	"qwolôrna": ["numeral", "million"],
	"qwossan": ["verb", "to remember"],
	"qwoŋbalas": ["adjective", "gorgeous"],
	"qwôl": ["noun group b", "dress, gown"],
	"qwôlar": ["noun group b", "hall, hallway"],
	"qwôra": ["noun group b", "chainmail, chain mail, maille"],
	"qwôren": ["verb", "to hug in a friendly way"],
	"raelesh": ["verb", "to die, to succumb"],
	"raeleshtil": ["adjective", "dead"],
	"raien": ["verb", "to own, to have"],
	"ralwe": ["noun group a", "ghost, apparition, wisp, spirit, genie"],
	"Ranûdel": ["noun group a", "kingdom of ranudel"],
	"rassae": ["noun group a", "leaf"],
	"rassil": ["noun group a", "forest"],
	"rende": ["adjective", "sick, infected, diseased"],
	"ressie": ["adjective", "plant seed"],
	"reŋmie": ["noun group a", "breast (mammal); one of a woman's breasts"],
	"rieldal": ["noun group b", "iron"],
	"rim": ["noun group a", "arm"],
	"rina": ["noun group b", "pouch, bag"],
	"rindalesh": ["verb", "to sing melodically"],
	"rindie": ["noun group a", "circle"],
	"roil": ["noun group c", "sludge, muck, decayed organic matter"],
	"ronathas": ["adjective", "great, mighty, powerful"],
	"rosse": ["noun group a", "window"],
	"rume": ["noun group a", "grass"],
	"rumeflowe": ["noun group a", "meadow, grassland, plains"],
	"rôcand": ["noun group c", "place of ruin, abandonment, or disaster; ancient ruin"],
	"rôn": ["noun group a", "mountain"],
	"rônberanae": ["noun group a", "mountain range"],
	"rûnas": ["adjective", "sweet, pleasant, nice, innocent"],
	"rûnathie": ["noun group a", "dream"],
	"rûndiel": ["numeral", "nine"],
	"rŷŋ": ["noun group a", "something ancient, old, mystical, or magical"],
	"rŷŋgwandar": ["noun group a", "wizardry"],
	"sa (2)": ["article", "definite article"],
	"sa": ["pronoun", "that (non-genitive)"],
	"saelas": ["adjective", "black"],
	"saerash": ["verb", "to end, to finish"],
	"saerassi": ["noun group a", "ending, end"],
	"sailan": ["verb", "to enlighten"],
	"sailas": ["adjective", "wise"],
	"sailassi": ["noun group a", "wisdom"],
	"saldassi": ["noun group a", "lightning"],
	"samai": ["adverb", "enough"],
	"sanash": ["verb", "to will, to ought (future tense verb)"],
	"sanaŋ": ["noun group a", "lizard"],
	"sani": ["pronoun", "that (genitive)"],
	"sathas": ["adjective", "grey, gray"],
	"seiren": ["verb", "to play an instument"],
	"seldiren": ["verb", "to frighten, to cause fear, to cause dread"],
	"selesh": ["verb", "to transform, to become, to turn into (with or without \"ci\")"],
	"selo": ["numeral", "six"],
	"sentie": ["noun group a", "priest"],
	"serafalassi": ["noun group a", "butterfly"],
	"serenas": ["adjective", "cute, pretty"],
	"serenevathas": ["adjective", "beautiful, gorgeous"],
	"serie": ["noun group a", "girl"],
	"sesufele": ["noun group a", "description, appeareance"],
	"sevir": ["noun group a", "force, invisible force"],
	"shaelda": ["noun group b", "lever, switch"],
	"shan": ["noun group c", "pain"],
	"sheb": ["noun group b", "boot, shoe"],
	"shelai": ["adjective/adverb", "such, so; like this, that sort of, that kind of"],
	"shele": ["noun group a", "thing, object"],
	"shelesse": ["noun group a", "mist"],
	"shielde": ["noun group a", "tree"],
	"shone": ["noun group a", "knowledge"],
	"shraeŋ": ["noun group b", "illusion"],
	"shrilie": ["noun group a", "chorus of birds"],
	"shrond": ["noun group b", "temple"],
	"shrunen": ["verb", "to buy"],
	"shrŷlwe": ["noun group a", "magical aura"],
	"shrŷna": ["noun group b", "hood, cowl"],
	"shrŷŋ": ["noun group b", "mirror"],
	"shwiŋ": ["noun group c", "bone"],
	"shôl": ["noun group b", "jewelry"],
	"shŷne": ["noun group a", "thyme"],
	"sidir": ["noun group b", "pants, trousers"],
	"silitha": ["noun group b", "writing"],
	"silssien": ["verb", "to like, to favour"],
	"sin": ["pronoun", "this (non-genitive)"],
	"sincultir": ["noun group a", "black hellebore (flower)"],
	"sini": ["pronoun", "this (genitive)"],
	"siten": ["verb", "to grab"],
	"siôrash": ["verb", "to bathe"],
	"siôren": ["verb", "to wash"],
	"siŋgae": ["noun group a", "salt"],
	"slacash": ["verb", "to scream, to screech"],
	"slande": ["adjective", "weird, strange"],
	"slantha": ["noun group b", "chemise, frock, shift; a long, linen underdress"],
	"slent": ["noun group b", "an undergarment shirt/tunic, usually made of linen or cotton"],
	"sloren": ["verb", "to scare, to unnerve, to make tremble"],
	"slôssie": ["noun group a", "juice"],
	"solonde": ["noun group a", "tranquility, serenity, calmness"],
	"solsse": ["noun group a", "minute"],
	"sontan": ["verb", "to cook"],
	"spacul": ["noun group c", "ghost, specter, apparition, spirit"],
	"spaid": ["noun group b", "scabbard"],
	"spiencelen": ["verb", "to violate someone, to rape"],
	"staelfe": ["noun group a", "tradition, custom"],
	"stûinde": ["noun group a", "animal, creature"],
	"suce": ["noun group a", "slime, ooze"],
	"swaesse": ["noun group a", "drink, beverage"],
	"swanze": ["noun group a", "sheep"],
	"swind": ["noun group b", "sign (for directions and text)"],
	"swintane": ["noun group a", "flute"],
	"swiŋye": ["noun group a", "type, kind, sort"],
	"sŷlae": ["noun group a", "swan"],
	"tacwel": ["noun group b", "hoe, cultivator, tiller"],
	"tael": ["noun group a", "god, deity"],
	"taent": ["noun group b", "a drum large enough that it's typically played whilst standing up"],
	"talaraŋ": ["noun group a", "sorcerer"],
	"taldaŋ": ["noun group a", "sorcery magic"],
	"tamalash": ["verb", "to shine brightly"],
	"tanten": ["verb", "to bake"],
	"tarien": ["noun group b", "gift, present"],
	"tassie": ["adjective", "crazy, mentally insane"],
	"tayandôr": ["noun group a", "orchid (flower)"],
	"taŋcan": ["verb", "to must, to shall"],
	"tecse": ["noun group a", "sea shell, snail shell, clam shell"],
	"telde": ["noun group a", "wonder"],
	"teltan": ["verb", "to oath, to promise, to commit an oath, to make a promise"],
	"telyash": ["verb", "to stand up straight"],
	"tende": ["adjective", "tall, high"],
	"tendessi": ["noun group a", "height"],
	"tenild": ["noun group b", "arm ring"],
	"terassi": ["noun group a", "lute"],
	"tesse": ["noun group a", "right"],
	"tessu": ["adverb", "rightwards"],
	"teŋgen": ["verb", "to arrive at, to reach, to get to"],
	"teŋgesh": ["verb", "to come"],
	"teŋnen": ["verb", "to hear"],
	"thael": ["noun group a", "clothing, apparel"],
	"thaiden": ["verb", "to stretch, to lengthen; to draw a bow"],
	"thaine": ["noun group a", "law, rules"],
	"thaisse": ["noun group a", "cloud, billow"],
	"thalashaŋ": ["noun group a", "druidry magic"],
	"thalassi": ["noun group a", "air"],
	"thas": ["numeral", "five"],
	"thash": ["verb", "to start, to begin"],
	"thelen": ["verb", "to find, to look for"],
	"there": ["adjective", "long"],
	"theren": ["adverb", "for a long time"],
	"theressi": ["noun group a", "length"],
	"thewan": ["verb", "to sew (with or without \"gai\" or \"mi\")"],
	"thiemen": ["verb", "to lead, to guide"],
	"thienas": ["numeral", "ten"],
	"thilde": ["noun group a", "ally, teammate"],
	"thilende": ["noun group a", "game, sport"],
	"thilu": ["adverb", "far"],
	"thime": ["noun group a", "silk"],
	"thiva": ["noun group b", "shears, scissors"],
	"thobae": ["noun group a", "finger"],
	"thomash": ["verb", "to want"],
	"thore": ["noun group a", "a loud, thunderous sound"],
	"thrande": ["noun group a", "orchard, garden"],
	"thrûvi": ["noun group b", "hay, thatch, dry grass"],
	"thrŷl": ["noun group b", "finger ring"],
	"thuŋ": ["noun group c", "fear, terror"],
	"thwossiesh": ["verb", "to would"],
	"thûca": ["numeral", "hundred"],
	"thûcen": ["verb", "to mean something"],
	"thûrda": ["noun group b", "polearm (weapon)"],
	"thûvala": ["noun group b", "spear"],
	"thŷlen": ["verb", "to taste"],
	"tilie": ["noun group a", "oath, promise"],
	"tiren": ["verb", "to close"],
	"tith": ["noun group b", "tower"],
	"tiôr": ["noun group b", "dwarf"],
	"trew": ["noun group a", "edelweiss (flower)"],
	"tulde": ["adjective", "lost, missing, gone"],
	"twaisen": ["verb", "to think, to guess"],
	"twaraŋ": ["noun group a", "thunder"],
	"twasa": ["numeral", "three"],
	"twûnesh": ["verb", "to wonder (with or without \"ci\")"],
	"twûssil": ["noun group a", "moon"],
	"twûssilglasse": ["noun group a", "moonlight"],
	"twûssilqwessie": ["noun group a", "moon elf"],
	"tônd": ["noun group b", "cauldron, pot"],
	"tûlen": ["verb", "to bind, to fixate (with or without \"min\")"],
	"tûmen": ["verb", "to hit, to strike"],
	"tŷlai": ["noun group a", "music"],
	"ulsela": ["noun group b", "glave, halberd, atgeir"],
	"ulumai ci": ["preposition", "used for"],
	"ulumai": ["preposition", "using with, prepared with"],
	"ulumailindu menden": ["verb", "to pay back, to repay, to tribute"],
	"ulumailindu": ["adverb", "in return"],
	"umash": ["verb", "to wait"],
	"ussas": ["adjective", "tired, exhausted"],
	"vace": ["verb", "to stab"],
	"vaere": ["noun group a", "fern"],
	"vai": ["preposition", "from"],
	"vana": ["noun group b", "mercenary"],
	"vancie": ["noun group a", "oak"],
	"vaondre": ["noun group a", "pine"],
	"vassash": ["verb", "to laugh"],
	"vasten": ["verb", "to rip, to tear"],
	"vayu": ["adverb", "away"],
	"velie": ["noun group a", "event, activity, gathering"],
	"velôma": ["noun group b", "parchment"],
	"veriŋnesh": ["verb", "to leave, to depart"],
	"ves": ["adjective", "some"],
	"vessi": ["noun group a", "place, location"],
	"viel": ["noun group a", "cause, origin, beginning"],
	"vil": ["noun group b", "metal"],
	"vim": ["conjunction", "which, who, whom, like, such as (not a question word)"],
	"vis": ["adverb", "yes"],
	"visses": ["adjective", "sharp"],
	"viôrda": ["noun group b", "cemetary"],
	"vlenten": ["verb", "to fling, to throw, to sling"],
	"vlussi": ["noun group a", "flower, bloom"],
	"vlûrash": ["verb", "to flow"],
	"vonen": ["verb", "to protect, to ward, to guard"],
	"vossae": ["noun group a", "brother"],
	"vucen": ["verb", "to use"],
	"vulsse": ["noun group a", "wolf"],
	"vôma": ["conjunction", "who, which"],
	"vônu": ["adverb", "near"],
	"vŷlissel": ["noun group b", "city"],
	"waelash": ["verb", "to wander astray"],
	"waelatil": ["adjective", "lost, alone, wandered off"],
	"waelfe": ["noun group a", "south"],
	"waide": ["noun group a", "linen"],
	"waiŋnen": ["noun group b", "to sway, to swing"],
	"wamesh": ["verb", "to emit a smell, to smell like (with or without \"ci\")"],
	"waren": ["verb", "to boil something"],
	"waresh": ["verb", "to boil"],
	"wasen": ["verb", "to surprise"],
	"weles": ["adjective", "yellow"],
	"welfu": ["adverb", "southward"],
	"wenwarie": ["noun group a", "camaraderie, chemistry (relationships)"],
	"windesh": ["verb", "to marry with, to wed (with \"min\")"],
	"windessi": ["verb", "marriage"],
	"windeyeldie": ["noun group a", "wedding"],
	"wiôlen": ["verb", "to burn, to set fire to; to scorch, to flame, to burn"],
	"wiôlesh": ["verb", "to burn"],
	"wond": ["noun group b", "haze"],
	"wune": ["adjective", "good"],
	"wôr": ["noun group a", "wind"],
	"yaer": ["noun group a", "bear"],
	"yaeran": ["verb", "to know"],
	"yalssi": ["noun group a", "violin, vielle, viola"],
	"yasen": ["verb", "to join"],
	"yaŋgstarssa": ["noun group b", "portal"],
	"yaŋu": ["adverb", "across"],
	"yeldie": ["noun group a", "festival"],
	"yelesh": ["verb", "to sing quietly"],
	"yelesiel": ["noun group a", "mother"],
	"yelon": ["noun group a", "thigh"],
	"yendrae": ["noun group a", "harp"],
	"yene": ["adjective", "young"],
	"yenessi": ["noun group a", "cattle, cow, yak"],
	"yome": ["adjective", "soft"],
	"yune": ["noun group a", "garden, yard"],
	"yôl": ["noun group a", "lock of hair"],
	"yômash": ["verb", "to groan, to moan"],
	"yûlae": ["noun group a", "power, might"],
	"zaelash": ["verb", "to grow"],
	"zaelen": ["verb", "to grow something"],
	"zaer": ["noun group b", "accident"],
	"zaerai": ["adverb", "accidentally"],
	"zaesh": ["noun group b", "house, home"],
	"zaeshe": ["noun group a", "home"],
	"zaevai": ["adverb", "accidentally"],
	"zaias": ["adjective", "white"],
	"zaimse": ["noun group a", "ash"],
	"zaitash": ["noun group c", "criminal, prisoner"],
	"zaiwen": ["verb", "to should, to ought"],
	"zalûdiem": ["noun group a", "angel, celestial"],
	"zane": ["noun group a", "neck"],
	"zanse": ["noun group a", "ice"],
	"zaranil": ["noun group a", "weather"],
	"zasha": ["noun group b", "knife, dagger"],
	"zath": ["noun group b", "fool"],
	"zathbie": ["adjective", "foolish, naive, unaware"],
	"zeile": ["noun group a", "insect"],
	"zelesh": ["verb", "to fall down"],
	"zemiel": ["noun group a", "emerald"],
	"zenesh": ["verb", "to smile"],
	"zenessi": ["noun group a", "smile"],
	"zerûla": ["noun group b", "merchant, seller, clerk"],
	"zerûlafelde": ["noun group a", "markets, fair, festival"],
	"zesûind": ["noun group b", "shop, store"],
	"ziena": ["noun group b", "necklace"],
	"zilen": ["verb", "to allow, to let; to set free"],
	"zirfai": ["verb", "divination; seidr, seiðr, seidur"],
	"zisses": ["adjective", "free"],
	"zlaemash": ["verb", "to blush, to fluster, to redden in the face"],
	"zlonden": ["verb", "to love passionately"],
	"zlondessi": ["noun group a", "romantic love"],
	"zlondiswe": ["noun group a", "romantic allure, sexual desire; allure, appeal, attractiveness"],
	"zolla": ["noun group b", "a gemstone embedded into metal"],
	"zonde": ["noun group a", "strait, channel (a landform where two seperate landmasses are almost touching but is seperated by deep water)"],
	"zrônel": ["noun group b", "crucible steel"],
	"zôlsil": ["noun group c", "damage"],
	"zôril": ["noun group a", "sanctuary, church, temple, mosque"],
	"zûinu": ["adverb", "through"],
	"zûlas": ["adjective", "visible"],
	"zûren": ["verb", "to draw"],
	"zŷl": ["noun group a", "drop of liquid"],
	"ôb": ["numeral", "one"],
	"ôces": ["preposition", "except"],
	"ôlaish": ["verb", "to sleep"],
	"ôlathvial": ["noun group b", "cloak, mantle"],
	"ôldaissa": ["noun group b", "alchoholic drink"],
	"ôldassi": ["noun group a", "plane of existence, dimension; world, realm"],
	"ôle": ["noun group a", "peace, calm, stillness"],
	"ôlir": ["noun group b", "smoke"],
	"ôlse": ["adjective", "deep"],
	"ôrbin": ["noun group c", "spider"],
	"ôrshen": ["verb", "to sadden, to depress"],
	"ôrshenassi": ["noun group a", "sadness, sorrow"],
	"ôrshes": ["adjective", "sad, unhappy"],
	"ôrshetele": ["adjective", "sad, unhappy, let down (because of something)"],
	"ôsa": ["noun group b", "rope"],
	"ôte": ["noun group a", "dirt, earth, soil"],
	"ûcanan": ["verb", "to choke someone"],
	"ûcanash": ["verb", "to choke on"],
	"ûga": ["noun group c", "ogre"],
	"ûllanor": ["noun group c", "sorrow, grief, heartache, heartbreak"],
	"ûne yaeran": ["verb", "to understand"],
	"ûne": ["adjective/adverb", "all"],
	"ûrci": ["noun group c", "orc, ork"],
	"ûthe": ["noun group a", "emotion, feelings"],
	"ŷcil": ["noun group c", "snake"],
	"ŷre": ["noun group a", "star"],
	"ŷrŋ": ["noun group a", "bell"],
};

const special_declensions = {};
