const word_type_short_form = {
	"noun group a": "n-a.",
	"noun group b": "n-b.",
	"noun group c": "n-c.",
	"adjective": "adj.",
	"adverb": "adv.",
	"adjective/adverb": "adj. & adv.",
	"verb": "v.",
	"conjunction": "c.",
	"phrase": "phr.",
	"onomatopeia": "on.",
	"expression": "exp.",
	"expression adverb": "expadv.",
	"interjection": "int.",
	"suffix": "suff.",
	"preposition": "pre.",
	"prefix": "pref.",
	"pronoun": "pron.",
	"auxiliary": "aux.",
	"numeral": "num."
};

const entry_words = [
	"-assi, -essi",
	"-bie",
	"-dae",
	"-iswe",
	"-nasse",
	"-nassul",
	"-ssul",
	"ael",
	"aelassi",
	"aelfe",
	"aelu",
	"aethe",
	"aide",
	"aides",
	"ailen",
	"ailesse",
	"aimaŋ",
	"ainandie",
	"ainas",
	"Ainassare",
	"Ainassareni ôle",
	"aindwe",
	"aiselen",
	"aiseleshnu",
	"aithavesh",
	"alaebai",
	"aldassil",
	"aldassil-glasse",
	"alem",
	"alie",
	"alowe",
	"alte",
	"altu",
	"alûande",
	"am",
	"amassa",
	"ambela",
	"an",
	"anassor",
	"anaŋen",
	"ancir",
	"andôl",
	"ansfem",
	"ansra",
	"ansrilô",
	"ansûrci",
	"ansûrvai",
	"antew",
	"anôsh",
	"aod",
	"aollen",
	"aonae",
	"aonash",
	"aontren",
	"aoslandie",
	"aossu",
	"arûnashe",
	"aseresh",
	"athu",
	"aŋnen",
	"baefan",
	"baelash",
	"baide",
	"baiden",
	"bain",
	"baldain",
	"balwe",
	"baon",
	"baranasse",
	"basseld",
	"basselden",
	"bawilen",
	"bawilesh",
	"beizie",
	"belas",
	"belde",
	"beldesh",
	"beranae",
	"bere",
	"bessar",
	"bethe",
	"bew",
	"bewesh",
	"bewwiel",
	"bicil",
	"bielen",
	"bienen",
	"bilsen",
	"bim",
	"bir",
	"birima",
	"bithe",
	"biôn",
	"biôra",
	"blean",
	"bleshen",
	"blewsse",
	"blewsse-bie",
	"blore",
	"bobewlie",
	"bollasse",
	"bollien",
	"bothen",
	"brame",
	"breid",
	"brelendas",
	"bries-aethe",
	"briesae",
	"brilesh",
	"brin",
	"briôrse",
	"bucul",
	"bwaile",
	"bwel",
	"bôr",
	"bôrand",
	"bûlwen",
	"bûlwenen",
	"bŷl",
	"cacul",
	"caelfassi",
	"caelfe-nasse",
	"caelfen",
	"caemen",
	"caiben",
	"Caidan",
	"caindie",
	"caindissi",
	"cairae",
	"cairan",
	"caissen",
	"caita",
	"caivas",
	"calamôr",
	"calaŋ",
	"caldash",
	"caldûi",
	"caltir",
	"calye",
	"canda",
	"cansu",
	"cantha",
	"cantir",
	"caotre",
	"carandon",
	"cassen",
	"cassil",
	"caŋ",
	"caŋ-nasse",
	"caŋnen",
	"caŋnentele",
	"celden",
	"celdôre",
	"celendra",
	"celene",
	"celevien",
	"celevietith",
	"celisse",
	"celondre",
	"celte",
	"cembalie",
	"cere",
	"certa",
	"cesh",
	"ci meltie",
	"ci",
	"cilie",
	"cindwe",
	"cinen",
	"cinûmaie",
	"cinûmaies",
	"cir",
	"cirem",
	"cirssi",
	"cithe",
	"claidwen",
	"clissa",
	"clud",
	"coil",
	"culden",
	"cushe",
	"cwen lindu",
	"cwen pônu",
	"cwen",
	"cwielen",
	"cwielesh",
	"côl",
	"cônde",
	"cûd",
	"cûiden",
	"cûidesh",
	"cûir",
	"cûle",
	"cûlentai",
	"cûsaŋ",
	"cûtwen",
	"cŷbas",
	"cŷlde",
	"cŷldu",
	"cŷle",
	"cŷŋ",
	"cŷŋ-bie",
	"cŷŋ-qwessie",
	"daelfa",
	"dagen",
	"dagssul",
	"dainasse",
	"dairash",
	"dalash",
	"dalashe",
	"damas",
	"damelde",
	"damwe",
	"damûr",
	"damûrssul",
	"dara",
	"darassil",
	"dasharen",
	"dashares",
	"dathas",
	"dathassi",
	"daŋga",
	"delen",
	"deleŋsten",
	"denalor",
	"denda",
	"dewa",
	"dewwollas",
	"diel",
	"diwen",
	"dora",
	"doron",
	"doru",
	"drai",
	"drai-nassul",
	"drai-vlûrash",
	"drasse",
	"drumesh",
	"drunden",
	"drôs",
	"dwaisa",
	"dwathollen",
	"dwaŋ",
	"dwaŋ-qwessie",
	"dwiwe",
	"dwonar",
	"dôranis",
	"dôre",
	"dôrla",
	"dôrse",
	"dûin",
	"dûlass",
	"Dûmatan",
	"dûmen",
	"dûmessi",
	"dŷl",
	"easil",
	"eindwe",
	"eis",
	"elefe",
	"elentre",
	"elessi",
	"elewwim",
	"elie",
	"emae",
	"emalûi",
	"emse",
	"emyash",
	"endecalen",
	"endûl",
	"ente",
	"entedae",
	"ere",
	"ereshe",
	"Eru Ilûvatar",
	"esash",
	"esien",
	"esûshwie",
	"etas",
	"ewesh",
	"ezele",
	"fa",
	"fabwe",
	"faeran",
	"fai",
	"faidesh",
	"faie",
	"failie",
	"failon",
	"falacaiwe",
	"falai",
	"falash",
	"falassi",
	"falye",
	"fana-nasse",
	"fanae",
	"fandai",
	"fashre",
	"fashres",
	"fassai",
	"fawash",
	"fayen",
	"feash",
	"feile",
	"felae",
	"felde",
	"feleth",
	"fen",
	"feres",
	"fessai",
	"fiele",
	"fim",
	"finden",
	"flaog",
	"flecwen",
	"fliwem",
	"flond",
	"flowe",
	"flowen-cairae",
	"folor",
	"fonash",
	"fonthis",
	"fonthiswe",
	"forona",
	"fruŋ",
	"fulde",
	"fuldu",
	"fushae",
	"futh",
	"fwagas",
	"fwashen",
	"fwaŋgend",
	"fwessie",
	"fwessiesh",
	"fûl",
	"fûles",
	"fûllan",
	"fûllassi",
	"fûr",
	"gael",
	"gai",
	"gaie",
	"gaish",
	"galash",
	"galen",
	"galiswe",
	"galssi",
	"gaŋnesh",
	"gaŋnessi",
	"gaŋse",
	"gessesh",
	"gessil",
	"gewme",
	"gi",
	"giel",
	"ginden",
	"glai",
	"glam-ialde",
	"glame",
	"glassan",
	"glasse",
	"glessi",
	"glessien",
	"gliefe",
	"Gliendwe",
	"glona",
	"glonash",
	"glorten",
	"gond",
	"goroth",
	"gow",
	"gulyesh",
	"guna",
	"gwaele",
	"gwaen",
	"gwaer",
	"gwaim",
	"gwainen",
	"gwalde",
	"gwamar",
	"gwandar",
	"gwandre",
	"gwane",
	"gwarse",
	"gwasan",
	"gwassem",
	"gweid",
	"gwelen",
	"gwen",
	"gwenden",
	"gwene",
	"gwentan",
	"gwer",
	"gwesen",
	"gwetha",
	"gwimul",
	"gwisse",
	"gwiôrien",
	"gwolor",
	"gwonde",
	"gwore",
	"gôash",
	"gôl",
	"gôl-lûandar",
	"gûil",
	"gûin",
	"gûlar",
	"gûlen",
	"gûnar",
	"gûrwen",
	"gŷl",
	"haed",
	"haeme",
	"haide",
	"hailasse",
	"haile-bie",
	"hailen",
	"haim",
	"hair",
	"haish",
	"haissen",
	"haivash",
	"haiŋ",
	"halûin",
	"hantan",
	"hasse",
	"heblen",
	"hele",
	"helerôn",
	"hembûin",
	"henyan",
	"henyassi",
	"heten",
	"hewas",
	"hiathien",
	"hicesh",
	"himai",
	"hithen",
	"hithes",
	"hiôlash",
	"hiŋgen",
	"hiŋgesh",
	"hob",
	"hube",
	"huntul",
	"hwassi",
	"hwer",
	"hweshe",
	"hwethae",
	"hwie",
	"hwil",
	"hwir",
	"hwissa",
	"hwiôrlath",
	"hwond",
	"hwônden",
	"hŷl",
	"i",
	"ia-",
	"ia-baiden",
	"ia-menden",
	"ialde",
	"ian",
	"iar",
	"iare",
	"icien",
	"icis",
	"iciswe",
	"ilare",
	"ilbu",
	"ilem",
	"indashas",
	"inde",
	"ine",
	"ine-",
	"ine-beizie",
	"ine-blewssebie",
	"ine-hailen",
	"ine-indashas",
	"ine-naimashnu",
	"ine-raeleshtil",
	"ine-silssien",
	"ine-thiemen",
	"inende",
	"innean",
	"inyas",
	"iraidôr",
	"irithie",
	"isil",
	"ithamae",
	"ivereld",
	"lacen",
	"laces",
	"lae",
	"lagwe",
	"laicen",
	"laire",
	"lande",
	"lannae",
	"lantre",
	"lanyan",
	"laog",
	"larun",
	"larun-bie",
	"lassai-bie",
	"lassaie",
	"lasthe",
	"lemya",
	"lendessil",
	"lerie",
	"lessar",
	"lewse",
	"lewwe",
	"linde",
	"lindu",
	"lisse",
	"lith",
	"liŋgash",
	"lode",
	"lodu",
	"loias",
	"losse",
	"loth",
	"luge",
	"lunas",
	"lôin",
	"lôiren",
	"lôl",
	"lômash",
	"lômen",
	"lôthie",
	"lûandar",
	"lûantir",
	"lûi",
	"lûind",
	"lûise",
	"lûl",
	"lûmassash",
	"lûnge",
	"lûngu",
	"lûr",
	"lûr-bie",
	"lŷŋ",
	"mai",
	"maiend",
	"maiepasvie",
	"maisse",
	"maissen",
	"maissentele",
	"maisses",
	"malen",
	"malentie",
	"malessi",
	"malya",
	"manaran",
	"mansie",
	"mashe",
	"mashele",
	"masinde",
	"maslom",
	"maslos",
	"massa",
	"masse",
	"massil",
	"massilen",
	"matha-nasse",
	"mathash",
	"maŋgar",
	"maŋgwon",
	"maŋwesh",
	"maŋye",
	"maŋyen",
	"maŋyesh",
	"meca",
	"meidel",
	"melan",
	"melanen",
	"mele",
	"meltie",
	"melya-bie",
	"melyan",
	"menden ulumailindu",
	"menden",
	"mere",
	"merie",
	"mesh",
	"mestan",
	"mi ena henyassi",
	"mi",
	"min",
	"mironden",
	"missi",
	"miu ôlaish",
	"miu",
	"miôren",
	"moile",
	"mollai",
	"mollie",
	"momil",
	"monae",
	"mond",
	"morda",
	"mul",
	"munas",
	"mô",
	"môlde",
	"môlde-hwond",
	"mône",
	"môre",
	"môril",
	"môrlas",
	"môrnan",
	"môth",
	"mûiral",
	"mûr",
	"mûrne",
	"mŷcûl",
	"mŷl",
	"naben",
	"nacen",
	"nacir",
	"naese",
	"nagwa",
	"naiand",
	"naie",
	"nail",
	"naimash",
	"nairande",
	"naiteshwe (1)",
	"naiteshwe (2)",
	"naiti-bie",
	"naitie",
	"naitien",
	"nalash",
	"naoca",
	"naocaita",
	"naore",
	"narash",
	"nare",
	"nashre",
	"nashres",
	"nasta",
	"naŋge",
	"naŋyash",
	"nean ... min lûl",
	"nean ... min mollie",
	"nean",
	"nenda",
	"nezile",
	"neŋ",
	"neŋtir",
	"nilzi",
	"ningse",
	"nirhala",
	"nisen",
	"nith",
	"niôr-nasse",
	"niôren",
	"niôŋ",
	"niŋ",
	"nobe",
	"nocor",
	"nolla",
	"nolyash",
	"nomas",
	"nossûiash",
	"nossûien",
	"nôga",
	"nôre",
	"nûen",
	"nûin",
	"nûlie",
	"nûmala",
	"nŷven",
	"oldassi",
	"Oldumel",
	"ollash",
	"olorda",
	"olûre",
	"omil",
	"paed",
	"pai",
	"paiash",
	"paicu",
	"paiden",
	"paien",
	"pala",
	"panen",
	"paon",
	"paon-aethe",
	"pase",
	"pashen",
	"pasiel",
	"path",
	"paŋ",
	"paŋge",
	"pelanôŋ",
	"pentren",
	"pentu",
	"pesse",
	"peŋ",
	"pin",
	"pinden",
	"plaire",
	"pleand",
	"possai",
	"pothe",
	"pôlla",
	"pôlômae",
	"pôlômash",
	"pônu",
	"pûllae",
	"pûllan",
	"pûmar",
	"pŷŋ",
	"qwa",
	"qwael",
	"qwael-bie",
	"qwaentan",
	"qwaithe",
	"qwalan",
	"qwande",
	"qwantash",
	"qwas",
	"qwash",
	"qwasheme",
	"qweldesh",
	"qwelya-qwessie",
	"qwelyas",
	"qwen",
	"qwerasir",
	"qwese",
	"qwessa",
	"qwessi-bie",
	"qwessi-dae",
	"qwessie",
	"qweth",
	"qwevie",
	"qwevien",
	"qwiresh",
	"qwiressi",
	"qwolôrna",
	"qwossan",
	"qwoŋbalas",
	"qwôl",
	"qwôlar",
	"qwôra",
	"qwôren",
	"qwŷl",
	"raelesh",
	"raeleshtil",
	"raien",
	"raithen",
	"ralwe",
	"Ranûdel",
	"rassae",
	"rassil",
	"rende",
	"rendessul",
	"ressie",
	"reŋmie",
	"rielda",
	"rim",
	"rina",
	"rindalesh",
	"rindie",
	"roil",
	"ronathas",
	"rosse",
	"rume",
	"rume-flowe",
	"rôcand",
	"rôl",
	"rôn",
	"rôn-beranae",
	"rûnas",
	"rûnathie",
	"rûndie",
	"rŷŋ",
	"rŷŋ-gwandar",
	"s'-",
	"sa (1)",
	"sa (2)",
	"saelas",
	"saerash",
	"saerassi",
	"sailan",
	"sailas",
	"sailassi",
	"saldassi",
	"samai",
	"sanash",
	"sanaŋ",
	"sani",
	"saru",
	"sathas",
	"seiren",
	"seldiren",
	"selesh",
	"selo",
	"sentie",
	"serafalassi",
	"serenas",
	"serenevathas",
	"serie",
	"sesufele",
	"sevir",
	"shaelda",
	"shan",
	"sheb",
	"shelai",
	"shele",
	"shelesse",
	"shelŷnas",
	"shielde",
	"shone",
	"shraeŋ",
	"shrilie",
	"shrond",
	"shrunen",
	"shrŷlwe",
	"shrŷna",
	"shrŷŋ",
	"shwiŋ",
	"shôl",
	"shûlen",
	"shŷne",
	"sidir",
	"silitha",
	"silssien",
	"sin",
	"sincultir",
	"sini",
	"siten",
	"siôrash",
	"siôren",
	"siŋga-lisse",
	"siŋgae",
	"slacash",
	"slande",
	"slantha",
	"slend",
	"sloren",
	"slores",
	"slôssie",
	"solonde",
	"solsse",
	"sontan",
	"spacul",
	"spaida",
	"spiencelen",
	"spiŋgwe",
	"spiŋgwesh",
	"staelfe",
	"stûinde",
	"suce",
	"swaesse",
	"swanze",
	"swind",
	"swintane",
	"swiŋye",
	"sŷlae",
	"tacwel",
	"tael",
	"taend",
	"talaraŋ",
	"taldaŋ",
	"tamalash",
	"tanda",
	"tanten",
	"tarien",
	"tassie",
	"tastassi",
	"tasten",
	"tayandôr",
	"taŋcan",
	"tecse",
	"telde",
	"teltan",
	"telyash",
	"tende",
	"tendiswe",
	"tenild",
	"terasse",
	"tesse",
	"tessu",
	"teŋgen",
	"teŋgesh",
	"teŋnen",
	"thael",
	"thaiden",
	"thaine",
	"thaisse",
	"thalashaŋ",
	"thalassi",
	"thas",
	"thash",
	"thelen",
	"there",
	"theren",
	"theressi",
	"thewan",
	"thiemen hassu",
	"thiemen",
	"thienas",
	"thilde",
	"thilende",
	"thilu",
	"thime",
	"thiva",
	"thobae",
	"thomash",
	"thore",
	"thrande",
	"throssen",
	"thrûvi",
	"thrŷl",
	"thuŋ",
	"thuŋnen",
	"thwossiesh",
	"thûca",
	"thûicen",
	"thûrda",
	"thûvala",
	"thŷlen",
	"tilie",
	"tima",
	"tiren",
	"tith",
	"tiôr",
	"trew",
	"tulde",
	"twaisen",
	"twaraŋ",
	"twasa",
	"tônd",
	"tûin",
	"tûlen",
	"tûlla",
	"tûmen",
	"tûnesh",
	"tûssil",
	"tûssil-glasse",
	"tûssil-qwessie",
	"tŷlai",
	"ulsela",
	"ulumai ci",
	"ulumai",
	"ulumai-lindu",
	"umash",
	"ussas",
	"vace",
	"vaere",
	"vai",
	"vana",
	"vancie",
	"vand",
	"vaondre",
	"vassash",
	"vasten",
	"vayu",
	"velie",
	"velôma",
	"veriŋnesh",
	"ves",
	"vessi",
	"viald",
	"viel",
	"vil",
	"vim",
	"vis",
	"visses",
	"viôrda",
	"vlenten",
	"vlussi",
	"vlûrash",
	"vonen",
	"vossae",
	"vucen",
	"vulsse",
	"vôma",
	"vônu",
	"vŷla",
	"waelash",
	"waelashtil",
	"waelfe",
	"waide",
	"waiŋnen",
	"wamesh",
	"waren",
	"waresh",
	"wasen",
	"weithi-nasse",
	"weithie",
	"weithien",
	"weles",
	"welfu",
	"wenwarie",
	"wilyen",
	"wilyessi",
	"wilyiswe",
	"winde-yeldie",
	"windesh",
	"windessi",
	"wiôlen",
	"wiôlesh",
	"wond",
	"wune",
	"wôr",
	"yaer",
	"yaldar",
	"yalssi",
	"yandas",
	"yasen",
	"yaŋgstarssa",
	"yaŋu",
	"yearen",
	"yeldie",
	"yelesh",
	"yelesiel",
	"yelon",
	"yendrae",
	"yene",
	"yenessi",
	"yethi-nasse",
	"yethien",
	"yome",
	"yune",
	"yôl",
	"yômash",
	"yûlae",
	"zaelash",
	"zaelen",
	"zaer",
	"zaerai",
	"zaesh",
	"zaeshe",
	"zaevai",
	"zaias",
	"zaimse",
	"zaitash",
	"zaiwen",
	"zalûdiem",
	"zane",
	"zanse",
	"zaranil",
	"zasha",
	"zath",
	"zath-bie",
	"zeile",
	"zelesh",
	"zemiel",
	"zene",
	"zenesh",
	"zerûla",
	"zerûla-felde",
	"zesûind",
	"ziena",
	"zilen",
	"zirfai",
	"zisses",
	"ziŋyash",
	"zlaemash",
	"zlonden",
	"zlondessi",
	"zlondiswe",
	"zolla",
	"zonde",
	"zôlsil",
	"zôril",
	"zôrnel",
	"zûinu",
	"zûlas",
	"zûren",
	"zŷl",
	"ôb",
	"ôces",
	"ôlaish",
	"ôlathvial",
	"ôle",
	"ôlir",
	"ôlse",
	"ôrbin",
	"ôrshen",
	"ôrshent i ere",
	"ôrshentele",
	"ôrshes",
	"ôrshessi",
	"ôsa",
	"ôte",
	"ûcanan",
	"ûcanash",
	"ûga",
	"ûllanor",
	"ûne",
	"ûrci",
	"ûthe",
	"ŷcil",
	"ŷla",
	"ŷndes",
	"ŷndûl",
	"ŷre",
	"ŷrŋ",
];

const entries = {
	"-assi, -essi": ["suffix", "-dom, -ment (attached to adjectives or verbs) (noun group a); adjective-to-noun suffix (noun group a)"],
	"-bie": ["adjective", "-like, -ly (forms adjectives)"],
	"-dae": ["suffix", "language suffix (noun group a)"],
	"-iswe": ["suffix", "-ness (attached to adjectives or verbs) (noun group a)"],
	"-nasse": ["suffix", "agent/worker suffix (noun group a)"],
	"-nassul": ["suffix", "agent/worker suffix (noun group c)"],
	"-ssul": ["suffix", "-dom, -ment (attached to adjectives or verbs) (noun group c)"],
	"ael": ["preposition", "out"],
	"aelassi": ["noun group a", "outside"],
	"aelfe": ["noun group a", "alfur (norse myth elves)"],
	"aelu": ["adverb", "out of"],
	"aethe": ["noun group a", "day"],
	"aide": ["noun group a", "nobility"],
	"aides": ["adjective", "noble"],
	"ailen": ["adverb", "early"],
	"ailesse": ["noun group a", "mountain peak"],
	"aimaŋ": ["noun group a", "ivy"],
	"ainandie": ["noun group a", "rite, ritual"],
	"ainas": ["adjective", "sacred, holy"],
	"Ainassare": ["noun group a", "Hærrulfyr/Hyrulfir's name in Ranûdan"],
	"Ainassareni ôle": ["phrase", "a greeting"],
	"aindwe": ["noun group a", "happiness, bliss"],
	"aiselen": ["verb", "to bless"],
	"aiseleshnu": ["phrase", "means \"thank you\""],
	"aithavesh": ["verb", "to be aware, to be cautious, to beware"],
	"alaebai": ["noun group a", "sun shafts"],
	"aldassil": ["noun group a", "sun"],
	"aldassil-glasse": ["noun group a", "sunlight"],
	"alem": ["noun group a", "memory"],
	"alie": ["noun group a", "color, colour"],
	"alowe": ["noun group a", "kid, child"],
	"alte": ["noun group a", "top"],
	"altu": ["preposition", "over, above"],
	"alûande": ["noun group a", "ocean"],
	"am": ["preposition", "about, around"],
	"amassa": ["noun group c", "monster"],
	"ambela": ["noun group b", "quiver"],
	"an": ["adverb", "but, yet, still"],
	"anassor": ["adjective", "rich, wealthy"],
	"anaŋen": ["verb", "to bite"],
	"ancir": ["noun group b", "army"],
	"andôl": ["noun group c", "enemy"],
	"ansfem": ["noun group a", "sister"],
	"ansra": ["conjunction", "how"],
	"ansrilô": ["conjunction", "what"],
	"ansûrci": ["conjunction", "where"],
	"ansûrvai": ["conjunction", "why"],
	"antew": ["noun group b", "table"],
	"anôsh": ["verb", "to go, to move"],
	"aod": ["numeral", "too many, too much"],
	"aollen": ["adverb", "after"],
	"aonae": ["noun group a", "song, singing"],
	"aonash": ["verb", "to sing"],
	"aontren": ["verb", "to follow"],
	"aoslandie": ["noun group a", "culture"],
	"aossu": ["numeral", "eight"],
	"arûnashe": ["noun group a", "religion"],
	"aseresh": ["verb", "vanish"],
	"athu": ["adverb", "up, upwards"],
	"aŋnen": ["verb", "to put, to place, to move something to a place"],
	"baefan": ["numeral", "thousand"],
	"baelash": ["verb", "to blush from embarrassment"],
	"baide": ["noun group a", "question"],
	"baiden": ["verb", "to ask"],
	"bain": ["adverb", "instantly, suddenly"],
	"baldain": ["noun group b", "baldric"],
	"balwe": ["noun group a", "cream"],
	"baon": ["noun group b", "payment, tribute"],
	"baranasse": ["noun group a", "bartender, barkeep"],
	"basseld": ["noun group c", "curse"],
	"basselden": ["verb", "to curse"],
	"bawilen": ["verb", "to deteriorate, to disintegrate, to break down"],
	"bawilesh": ["noun group a", "to dissipate, to disintegrate, to turn into nothing"],
	"beizie": ["noun group a", "people, folk"],
	"belas": ["adjective", "other, another"],
	"belde": ["noun group a", "dance"],
	"beldesh": ["verb", "to dance"],
	"beranae": ["noun group a", "family"],
	"bere": ["pronoun", "they, them"],
	"bessar": ["adjective", "warm"],
	"bethe": ["noun group a", "big cat"],
	"bew": ["noun group a", "lip"],
	"bewesh": ["verb", "to play, to entertain oneself"],
	"bewwiel": ["noun group a", "foreigner, stranger"],
	"bicil": ["noun group c", "garbage"],
	"bielen": ["verb", "to give, to grant"],
	"bienen": ["verb", "to send"],
	"bilsen": ["verb", "to guide"],
	"bim": ["noun group a", "boy"],
	"bir": ["pronoun", "he, him"],
	"birima": ["noun group b", "farm, plantation"],
	"bithe": ["noun group a", "man, male"],
	"biôn": ["noun group b", "lesson"],
	"biôra": ["noun group b", "inn, hotel"],
	"blean": ["verb", "to feel an emotion; to feel pain"],
	"bleshen": ["verb", "to touch, to feel something physical"],
	"blewsse": ["noun group a", "comfort"],
	"blewsse-bie": ["adjective", "comfortable"],
	"blore": ["noun group a", "wool"],
	"bobewlie": ["noun group a", "potato"],
	"bollasse": ["noun group a", "wood"],
	"bollien": ["noun group b", "vase"],
	"bothen": ["verb", "to destroy, to break"],
	"brame": ["noun group a", "carrot"],
	"breid": ["noun group b", "basket"],
	"brelendas": ["adjective", "complex, intricate"],
	"bries-aethe": ["noun group a", "yesterday (contraction of briesae aethe)"],
	"briesae": ["noun group a", "experience, memory"],
	"brilesh": ["verb", "to rest, to take a break"],
	"brin": ["adverb", "before"],
	"briôrse": ["noun group a", "wasp"],
	"bucul": ["noun group c", "skull"],
	"bwaile": ["noun group a", "deer"],
	"bwel": ["noun group c", "poison"],
	"bôr": ["noun group a", "swamp, bog"],
	"bôrand": ["noun group b", "letter (a message)"],
	"bûlwen": ["noun group b", "shield"],
	"bûlwenen": ["verb", "to shield, to protect"],
	"bŷl": ["noun group a", "sprout, shoot of plant"],
	"cacul": ["noun group c", "troll"],
	"caelfassi": ["noun group a", "adventure, exploit"],
	"caelfe-nasse": ["noun group a", "adventurer"],
	"caelfen": ["verb", "to go on an adventure"],
	"caemen": ["verb", "to seem like"],
	"caiben": ["verb", "to wound"],
	"Caidan": ["noun group a", "spring"],
	"caindie": ["noun group a", "allegiance, fidelity"],
	"caindissi": ["noun group a", "alliance"],
	"cairae": ["noun group a", "crack (thin opening or damage on a hard surface)"],
	"cairan": ["verb", "to crack, to split"],
	"caissen": ["verb", "to grind, to crush"],
	"caita": ["noun group b", "axe (weapon)"],
	"caivas": ["noun group b", "mace (weapon)"],
	"calamôr": ["noun group a", "world, universe"],
	"calaŋ": ["noun group b", "cup, mug, tankard, goblet"],
	"caldash": ["verb", "to appear"],
	"caldûi": ["noun group a", "twilight"],
	"caltir": ["noun group a", "cabbage, lettuce"],
	"calye": ["noun group a", "bay"],
	"canda": ["noun group b", "helmet"],
	"cansu": ["adverb", "eastward"],
	"cantha": ["noun group b", "cloth, fabric"],
	"cantir": ["noun group a", "block, cube, brick"],
	"caotre": ["noun group a", "east"],
	"carandon": ["noun group a", "tower karst, extremely jagged mountain"],
	"cassen": ["verb", "to carve"],
	"cassil": ["noun group a", "dust, powder"],
	"caŋ": ["noun group a", "arcane spell"],
	"caŋ-nasse": ["noun group a", "wizard"],
	"caŋnen": ["verb", "to bend, to twist"],
	"caŋnentele": ["adjective", "bent, twisted, crooked"],
	"celden": ["verb", "to grasp, to grab, to manhandle, to hold forcefully"],
	"celdôre": ["noun group a", "makeup, perfume, body care product, cream"],
	"celendra": ["noun group b", "crown, circlet"],
	"celene": ["adjective", "safe, secure"],
	"celevien": ["verb", "to watch"],
	"celevietith": ["noun group b", "watchtower"],
	"celisse": ["noun group a", "horse"],
	"celondre": ["noun group b", "glass"],
	"celte": ["noun group a", "meat, flesh"],
	"cembalie": ["noun group a", "meeting, gathering, assemblage, assembly (archaically called a thing)"],
	"cere": ["noun group a", "health"],
	"certa": ["noun group a", "letter, rune"],
	"cesh": ["verb", "to jump, to hop"],
	"ci meltie": ["conjunction", "while, whilst"],
	"ci": ["preposition", "towards, to, at; for a person or an object"],
	"cilie": ["adjective/adverb", "perfect, perfectly"],
	"cindwe": ["noun group a", "hope"],
	"cinen": ["verb", "to dig"],
	"cinûmaie": ["noun group a", "royality"],
	"cinûmaies": ["adjective", "royal"],
	"cir": ["adjective", "new"],
	"cirem": ["noun group b", "sword (weapon)"],
	"cirssi": ["noun group a", "news, tidings"],
	"cithe": ["noun group a", "ear"],
	"claidwen": ["verb", "to summon, to call upon, to call for"],
	"clissa": ["noun group b", "saddle"],
	"clud": ["noun group b", "fork"],
	"coil": ["noun group c", "death"],
	"culden": ["verb", "to build"],
	"cushe": ["noun group a", "nut"],
	"cwen lindu": ["verb", "to put away"],
	"cwen pônu": ["verb", "to take out, to bring out"],
	"cwen": ["verb", "to see, to look at"],
	"cwielen": ["verb", "to freeze"],
	"cwielesh": ["verb", "to become frozen, to freeze"],
	"côl": ["adverb", "no"],
	"cônde": ["noun group a", "teeth, fang"],
	"cûd": ["noun group c", "skeleton"],
	"cûiden": ["verb", "to wake someone/something up"],
	"cûidesh": ["verb", "to wake up, to become awake, to awaken"],
	"cûir": ["noun group a", "sight, view"],
	"cûle": ["adjective", "alone"],
	"cûlentai": ["noun group a", "the eternal mist; the ethereal blue mist that surrounds the mountains of ranudel"],
	"cûsaŋ": ["noun group a", "vine"],
	"cûtwen": ["noun group b", "toilet"],
	"cŷbas": ["adjective", "thirsty"],
	"cŷlde": ["noun group a", "west"],
	"cŷldu": ["adverb", "westward"],
	"cŷle": ["noun group a", "a fog pool formed in the ground when the morning fog dissipates"],
	"cŷŋ": ["noun group a", "cold"],
	"cŷŋ-bie": ["adjective", "cold"],
	"cŷŋ-qwessie": ["noun group a", "cold elf"],
	"daelfa": ["numeral", "four"],
	"dagen": ["verb", "to kill, to slay, to murder"],
	"dagssul": ["noun group c", "murder"],
	"dainasse": ["noun group a", "cut crystal, cut gem"],
	"dairash": ["verb", "to hurry, to make haste"],
	"dalash": ["verb", "to redden"],
	"dalashe": ["noun group a", "crystal, gem"],
	"damas": ["adjective", "red"],
	"damelde": ["noun group a", "language"],
	"damwe": ["noun group a", "darkness, gloom, murk, shadow"],
	"damûr": ["adjective", "dark, dim"],
	"damûrssul": ["noun group c", "darkness, shadow; a dark hiding spot"],
	"dara": ["noun group b", "copper"],
	"darassil": ["noun group a", "glade, forest clearing"],
	"dasharen": ["verb", "to startle, to frighten, to scare, to shock (fleeting scare)"],
	"dashares": ["adjective", "scared, startled"],
	"dathas": ["adjective", "hard to break, sturdy"],
	"dathassi": ["noun group b", "locking mechanicism, padlock, lock system"],
	"daŋga": ["noun group b", "ore"],
	"delen": ["verb", "to hold"],
	"deleŋsten": ["verb", "to experience, to feel"],
	"denalor": ["noun group c", "oblivion, devastation"],
	"denda": ["noun group b", "shelf"],
	"dewa": ["noun group b", "quill, pen"],
	"dewwollas": ["adjective", "lush"],
	"diel": ["noun group a", "fish"],
	"diwen": ["verb", "to need, to require"],
	"dora": ["noun group b", "clan, tribe"],
	"doron": ["noun group b", "castle, fortress"],
	"doru": ["adverb", "only (count)"],
	"drai": ["noun group c", "blood"],
	"drai-nassul": ["noun group c", "vampire"],
	"drai-vlûrash": ["verb", "to bleed"],
	"drasse": ["noun group a", "lore, history; story, tale"],
	"drumesh": ["verb", "to hum"],
	"drunden": ["verb", "to ride"],
	"drôs": ["adjective", "blue"],
	"dwaisa": ["noun group b", "brass"],
	"dwathollen": ["verb", "to control, to manipulate, to rule over"],
	"dwaŋ": ["noun group a", "night"],
	"dwaŋ-qwessie": ["noun group a", "night elf (world of warcraft)"],
	"dwiwe": ["noun group a", "beam of light or magic"],
	"dwonar": ["adjective", "dangerous"],
	"dôranis": ["noun group b", "message"],
	"dôre": ["conjunction", "generic question word; whether, which, if"],
	"dôrla": ["noun group b", "bucket"],
	"dôrse": ["noun group a", "penis"],
	"dûin": ["noun group a", "field"],
	"dûlass": ["noun group b", "arrow (weapon)"],
	"Dûmatan": ["noun group a", "autumn, fall"],
	"dûmen": ["verb", "to count"],
	"dûmessi": ["noun group a", "count, amount; number"],
	"dŷl": ["noun group a", "dew"],
	"easil": ["noun group b", "bed"],
	"eindwe": ["noun group a", "waterfall"],
	"eis": ["adverb", "also, too"],
	"elefe": ["noun group a", "floor, ground (built)"],
	"elentre": ["noun group a", "elm"],
	"elessi": ["noun group a", "vegetable"],
	"elewwim": ["noun group a", "medicine"],
	"elie": ["noun group a", "will, willpower, spirit"],
	"emae": ["noun group a", "spirit, soul"],
	"emalûi": ["noun group a", "a giant, enourmous river"],
	"emse": ["noun group a", "(anthropology) face"],
	"emyash": ["verb", "to gleam, to glow"],
	"endecalen": ["verb", "to surround; to flank"],
	"endûl": ["noun group b", "gate"],
	"ente": ["adjective", "common"],
	"entedae": ["noun group a", "the common language"],
	"ere": ["pronoun", "i, me"],
	"ereshe": ["noun group a", "plant"],
	"Eru Ilûvatar": ["noun group a", "Eru Ilúvatar's name in Ranûdan"],
	"esash": ["verb", "to speak, to talk"],
	"esien": ["verb", "to say"],
	"esûshwie": ["noun group a", "herb"],
	"etas": ["adjective", "any, anything"],
	"ewesh": ["verb", "to cry silently, to weep, to tear up"],
	"ezele": ["adjective", "green"],
	"fa": ["preposition", "at a place"],
	"fabwe": ["noun group a", "berry"],
	"faeran": ["verb", "to share"],
	"fai": ["conjunction", "if"],
	"faidesh": ["verb", "to suppose, to assume"],
	"faie": ["adverb", "there"],
	"failie": ["noun group a", "fey, fae, fairy, faerie"],
	"failon": ["noun group b", "feast, banquet"],
	"falacaiwe": ["noun group a", "water spring, hot spring, volcanic spring; source of water"],
	"falai": ["adverb", "maybe, might, probably, could"],
	"falash": ["verb", "to fly"],
	"falassi": ["noun group a", "flight"],
	"falye": ["noun group a", "sea"],
	"fana-nasse": ["noun group a", "artisan, artist"],
	"fanae": ["noun group a", "art"],
	"fandai": ["noun group a", "awe, terror"],
	"fashre": ["noun group a", "respect, obedience"],
	"fashres": ["adjective", "respectful"],
	"fassai": ["article", "those"],
	"fawash": ["verb", "to blow"],
	"fayen": ["verb", "to smell, to sniff"],
	"feash": ["verb", "to go, to travel, to fare"],
	"feile": ["noun group a", "fur"],
	"felae": ["noun group a", "trait, attribute, property"],
	"felde": ["noun group a", "road, trail, path, street"],
	"feleth": ["noun group b", "curtain, veil"],
	"fen": ["verb", "to try, to attempt"],
	"feres": ["adjective", "friendly, good-mannered, nice"],
	"fessai": ["article", "these"],
	"fiele": ["noun group b", "ale"],
	"fim": ["noun group a", "hair"],
	"finden": ["verb", "to put on, to wear"],
	"flaog": ["noun group c", "internal organ"],
	"flecwen": ["verb", "to roast"],
	"fliwem": ["noun group a", "realm, world, land, area; place, location"],
	"flond": ["noun group b", "cart, wagon"],
	"flowe": ["noun group a", "land, ground"],
	"flowen-cairae": ["noun group a", "crevasse"],
	"folor": ["adjective", "poor"],
	"fonash": ["verb", "to lay down"],
	"fonthis": ["adjective", "large, big"],
	"fonthiswe": ["noun group a", "largeness, bigness, size"],
	"forona": ["noun group b", "soldier"],
	"fruŋ": ["noun group b", "prison cell"],
	"fulde": ["noun group a", "north"],
	"fuldu": ["adverb", "northward"],
	"fushae": ["noun group a", "bush, tall grass"],
	"futh": ["noun group c", "demon, devil"],
	"fwagas": ["adjective", "disgusting, gross"],
	"fwashen": ["verb", "to forge, to smith; to make with metal"],
	"fwaŋgend": ["noun group b", "anvil"],
	"fwessie": ["noun group a", "prayer"],
	"fwessiesh": ["verb", "to pray"],
	"fûl": ["noun group c", "evil"],
	"fûles": ["adjective", "evil, wicked"],
	"fûllan": ["verb", "to sense"],
	"fûllassi": ["noun group a", "sense, feel, emotion"],
	"fûr": ["preposition", "off"],
	"gael": ["noun group a", "egg"],
	"gai": ["preposition", "on"],
	"gaie": ["noun group a", "elk"],
	"gaish": ["verb", "to dare"],
	"galash": ["verb", "to gallop"],
	"galen": ["verb", "to hate"],
	"galiswe": ["noun group a", "hatredness"],
	"galssi": ["noun group a", "hatred"],
	"gaŋnesh": ["verb", "to chant, to speak an incantation"],
	"gaŋnessi": ["noun group a", "chant, incantation"],
	"gaŋse": ["noun group a", "drum"],
	"gessesh": ["verb", "to breathe"],
	"gessil": ["noun group b", "room"],
	"gewme": ["noun group a", "fog"],
	"gi": ["preposition", "for a person; for a period of time in the future"],
	"giel": ["noun group a", "honey"],
	"ginden": ["verb", "to paint"],
	"glai": ["adverb", "unwell, badly"],
	"glam-ialde": ["noun group a", "prince"],
	"glame": ["noun group a", "king"],
	"glassan": ["verb", "to listen"],
	"glasse": ["noun group a", "light"],
	"glessi": ["noun group a", "knot"],
	"glessien": ["verb", "to tie a knot"],
	"gliefe": ["noun group a", "scale (of a reptile or fish)"],
	"Gliendwe": ["noun group a", "winter"],
	"glona": ["noun group b", "seat"],
	"glonash": ["verb", "to sit down"],
	"glorten": ["verb", "to hurt, to cause pain to"],
	"gond": ["noun group c", "trap"],
	"goroth": ["noun group c", "horror, abomination, atrocity"],
	"gow": ["noun group b", "group, party, company"],
	"gulyesh": ["verb", "to melt"],
	"guna": ["noun group b", "currency, money"],
	"gwaele": ["noun group a", "queen"],
	"gwaen": ["noun group b", "stairs"],
	"gwaer": ["noun group b", "door"],
	"gwaim": ["noun group a", "sound, noise"],
	"gwainen": ["verb", "to heal a wound"],
	"gwalde": ["adjective", "old, aged"],
	"gwamar": ["adjective", "bad"],
	"gwandar": ["noun group a", "magic"],
	"gwandre": ["noun group a", "a poetic, flowing song; a ballad"],
	"gwane": ["noun group a", "jade"],
	"gwarse": ["noun group a", "hornet"],
	"gwasan": ["verb", "to exercise, to work out"],
	"gwassem": ["noun group b", "a mineshaft"],
	"gweid": ["noun group b", "goblet, chalice"],
	"gwelen": ["adverb", "late"],
	"gwen": ["pronoun", "you"],
	"gwenden": ["verb", "to craft, to create, to make"],
	"gwene": ["noun group a", "shadow"],
	"gwentan": ["verb", "to write"],
	"gwer": ["adjective", "stupid"],
	"gwesen": ["verb", "to kiss, to peck"],
	"gwetha": ["noun group b", "wardrobe"],
	"gwimul": ["noun group a", "disease, sickness, illness, malady"],
	"gwisse": ["noun group a", "second (a unit of time)"],
	"gwiôrien": ["noun group b", "scroll"],
	"gwolor": ["noun group b", "anger"],
	"gwonde": ["noun group a", "ravine, canyon, gorge"],
	"gwore": ["noun group a", "mouth"],
	"gôash": ["verb", "to rot, to decay"],
	"gôl": ["noun group b", "fire torch"],
	"gôl-lûandar": ["noun group b", "fire steel, fire striker"],
	"gûil": ["noun group a", "choir"],
	"gûin": ["noun group a", "a soft, ethereal light"],
	"gûlar": ["adjective", "low, short"],
	"gûlen": ["verb", "to eat"],
	"gûnar": ["adjective", "barbaric, ungraceful, crude"],
	"gûrwen": ["noun group b", "ship"],
	"gŷl": ["noun group a", "year"],
	"haed": ["noun group b", "chair, stool"],
	"haeme": ["noun group a", "human"],
	"haide": ["noun group a", "flow, stream, run; way, path"],
	"hailasse": ["noun group a", "obedience, submission"],
	"haile-bie": ["adjective", "obedient, submissive"],
	"hailen": ["verb", "to obey, to listen"],
	"haim": ["noun group a", "gender"],
	"hair": ["adjective/adverb", "loud"],
	"haish": ["noun group b", "hauberk"],
	"haissen": ["verb", "to hug, to embrace"],
	"haivash": ["verb", "to rise"],
	"haiŋ": ["noun group a", "storm"],
	"halûin": ["noun group c", "dragon, wyrm"],
	"hantan": ["verb", "to throw, to lob, to chuck"],
	"hasse": ["noun group a", "hand"],
	"heblen": ["verb", "to keep"],
	"hele": ["noun group a", "fire"],
	"helerôn": ["noun group a", "volcano"],
	"hembûin": ["noun group a", "salmon"],
	"henyan": ["verb", "to understand, to comprehend"],
	"henyassi": ["noun group a", "understanding, comprehension"],
	"heten": ["noun group b", "cubit"],
	"hewas": ["adjective", "brown"],
	"hiathien": ["verb", "to provoke, to aggravate, to anger"],
	"hicesh": ["verb", "to skip around, to frolick merrily"],
	"himai": ["noun group b", "shirt, tunic"],
	"hithen": ["verb", "to anger"],
	"hithes": ["adjective", "angry"],
	"hiôlash": ["verb", "to jump, to leap"],
	"hiŋgen": ["verb", "to train, to teach"],
	"hiŋgesh": ["verb", "to practice, to train"],
	"hob": ["noun group c", "goblin"],
	"hube": ["noun group a", "nose"],
	"huntul": ["noun group c", "war"],
	"hwassi": ["noun group a", "hour"],
	"hwer": ["adjective/adverb", "fast, quick"],
	"hweshe": ["noun group a", "sand"],
	"hwethae": ["noun group a", "list, collection"],
	"hwie": ["noun group a", "sweat"],
	"hwil": ["noun group a", "time"],
	"hwir": ["adjective", "simple"],
	"hwissa": ["numeral", "seven"],
	"hwiôrlath": ["noun group b", "school, academy"],
	"hwond": ["noun group b", "guard, guardsman, patroller, watchman"],
	"hwônden": ["verb", "to soak, to drench"],
	"hŷl": ["noun group a", "forest heather"],
	"i": ["article", "substitute article for the subject case"],
	"ia-": ["prefix", "re- suffix"],
	"ia-baiden": ["verb", "to answer"],
	"ia-menden": ["verb", "to pay back, to repay, to tribute (informal)"],
	"ialde": ["noun group a", "son"],
	"ian": ["noun group b", "bridge"],
	"iar": ["adjective", "hot"],
	"iare": ["noun group a", "heat"],
	"icien": ["verb", "to like, to adore, to be endeared by"],
	"icis": ["adjective", "adoreable, cute, endearing"],
	"iciswe": ["noun group a", "adoreableness, cuteness, endearingness"],
	"ilare": ["noun group a", "sky"],
	"ilbu": ["adverb", "down, downwards"],
	"ilem": ["noun group a", "ink"],
	"indashas": ["adjective/adverb", "possible"],
	"inde": ["verb", "to do, to act (no infinitive)"],
	"ine": ["numeral", "zero"],
	"ine-": ["prefix", "negator prefix"],
	"ine-beizie": ["noun group a", "no one"],
	"ine-blewssebie": ["adjective", "uncomfortable"],
	"ine-hailen": ["verb", "to disobey, to defy"],
	"ine-indashas": ["adjective/adverb", "impossible"],
	"ine-naimashnu": ["phrase", "means \"dont worry\""],
	"ine-raeleshtil": ["adjective", "eternal, forever, undying"],
	"ine-silssien": ["verb", "to dislike"],
	"ine-thiemen": ["verb", "to mislead"],
	"inende": ["verb", "to do not"],
	"innean": ["verb", "to not be"],
	"inyas": ["adjective", "small, little"],
	"iraidôr": ["noun group a", "ruby"],
	"irithie": ["noun group a", "silver"],
	"isil": ["noun group a", "eye"],
	"ithamae": ["verb", "painting"],
	"ivereld": ["noun group b", "mission, quest"],
	"lacen": ["verb", "to scare, to frighten"],
	"laces": ["adjective", "scared, frightened"],
	"lae": ["pronoun", "she, her"],
	"lagwe": ["noun group a", "oil"],
	"laicen": ["verb", "to sneak, to go stealthily, to move quietly, to crouch"],
	"laire": ["noun group a", "poem"],
	"lande": ["adjective", "empty"],
	"lannae": ["noun group a", "woman"],
	"lantre": ["noun group a", "lake"],
	"lanyan": ["verb", "to weave"],
	"laog": ["noun group c", "tar, pitch"],
	"larun": ["noun group b", "desert, desolate land"],
	"larun-bie": ["adjective", "desolate, deserted, completely empty"],
	"lassai-bie": ["adjective", "alluring, attractive, appealing"],
	"lassaie": ["noun group a", "allure, appeal, attractiveness"],
	"lasthe": ["noun group a", "water well"],
	"lemya": ["noun group a", "smell, aroma, fragrance"],
	"lendessil": ["noun group a", "grove"],
	"lerie": ["noun group a", "lyre"],
	"lessar": ["adjective", "absentminded, thoughtless, unwise; ambitionless, unfocused, wandering"],
	"lewse": ["noun group a", "fat, grease"],
	"lewwe": ["noun group a", "smell, odor, aroma"],
	"linde": ["noun group a", "back"],
	"lindu": ["adverb", "backwards"],
	"lisse": ["noun group a", "water"],
	"lith": ["noun group b", "dust, grime"],
	"liŋgash": ["verb", "to trail, to leave a trail"],
	"lode": ["noun group a", "left"],
	"lodu": ["adverb", "leftwards"],
	"loias": ["adjective", "pink"],
	"losse": ["noun group a", "snow"],
	"loth": ["noun group b", "bread"],
	"luge": ["noun group a", "mud, ooze"],
	"lunas": ["adjective", "mild, gentle, kind, nice, friendly, sweet"],
	"lôin": ["adverb", "now"],
	"lôiren": ["verb", "to beg, to plead"],
	"lôl": ["noun group a", "hill"],
	"lômash": ["verb", "to learn"],
	"lômen": ["verb", "to teach"],
	"lôthie": ["noun group a", "temple, shrine, religious place"],
	"lûandar": ["noun group b", "steel"],
	"lûantir": ["noun group b", "crossbow (weapon)"],
	"lûi": ["noun group a", "river"],
	"lûind": ["noun group b", "village, town, settlement"],
	"lûise": ["noun group a", "month"],
	"lûl": ["noun group a", "life"],
	"lûmassash": ["verb", "to cry, to weep"],
	"lûnge": ["noun group a", "bottom"],
	"lûngu": ["preposition", "under"],
	"lûr": ["adjective/adverb", "slow, slowly"],
	"lûr-bie": ["adjective/adverb", "lazy"],
	"lŷŋ": ["noun group a", "willow"],
	"mai": ["adverb", "well"],
	"maiend": ["noun group b", "mead"],
	"maiepasvie": ["noun group b", "cathedral"],
	"maisse": ["noun group a", "happiness, joy, glee"],
	"maissen": ["verb", "to cheer up"],
	"maissentele": ["adjective", "happy, joyful, gleeful (because of something); proud"],
	"maisses": ["adjective", "happy, joyful, gleeful"],
	"malen": ["verb", "to mix, to blend, to stir"],
	"malentie": ["noun group a", "blue poppy (flower)"],
	"malessi": ["noun group a", "mix, blend, concoction; chaotic group, melting pot of things; compilation"],
	"malya": ["noun group b", "government"],
	"manaran": ["verb", "to escape, to flee"],
	"mansie": ["noun group a", "diamond"],
	"mashe": ["noun group a", "food"],
	"mashele": ["noun group a", "meal"],
	"masinde": ["noun group a", "result, conclusion, fate, destiny"],
	"maslom": ["noun group a", "ball, sphere"],
	"maslos": ["adjective", "orange (color)"],
	"massa": ["noun group b", "mattress"],
	"masse": ["noun group a", "bird"],
	"massil": ["noun group a", "name"],
	"massilen": ["verb", "to name, to call"],
	"matha-nasse": ["noun group a", "worker"],
	"mathash": ["verb", "to work, to labour"],
	"maŋgar": ["adjective", "brave, bold, courageous"],
	"maŋgwon": ["noun group c", "smell, stench"],
	"maŋwesh": ["verb", "to stink, to emit a bad smell, to emit a stench"],
	"maŋye": ["noun group a", "potion, concoction, mixture"],
	"maŋyen": ["verb", "to invoke, to provoke, to rouse, to stir"],
	"maŋyesh": ["verb", "to arrive in geological season; to be invoked, to be provoked, to be roused"],
	"meca": ["noun group b", "brick"],
	"meidel": ["noun group b", "shovel"],
	"melan": ["noun group a", "help, assistance"],
	"melanen": ["verb", "to help"],
	"mele": ["adjective", "melodic, lyrical"],
	"meltie": ["conjunction", "when"],
	"melya-bie": ["adjective", "lovely, adorable"],
	"melyan": ["verb", "to love, to cherish"],
	"menden ulumailindu": ["verb", "to pay back, to repay, to tribute (formal)"],
	"menden": ["verb", "to pay"],
	"mere": ["noun group b", "favourite"],
	"merie": ["noun group a", "friend"],
	"mesh": ["verb", "to can, to be able to"],
	"mestan": ["verb", "to heal, to cure, to save (from a disease) (without, or with \"vai\" + from what)"],
	"mi ena henyassi": ["adverb", "means \"in my own words\" or \"from what i know\""],
	"mi": ["preposition", "in, inside; in a period of time in the past"],
	"min": ["adverb", "by, beside, with; of"],
	"mironden": ["verb", "to infect"],
	"missi": ["noun group a", "inside"],
	"miu ôlaish": ["verb", "to fall asleep"],
	"miu": ["adverb", "into"],
	"miôren": ["verb", "to care for, to nurture"],
	"moile": ["noun group a", "hole"],
	"mollai": ["adverb", "more"],
	"mollie": ["noun group a", "work, labour, job"],
	"momil": ["noun group a", "owl"],
	"monae": ["noun group a", "body, torso"],
	"mond": ["noun group c", "trouble, problem"],
	"morda": ["noun group b", "map"],
	"mul": ["noun group c", "slave"],
	"munas": ["adjective", "sleepy, tired, drowsy"],
	"mô": ["conjunction", "or"],
	"môlde": ["noun group b", "battle"],
	"môlde-hwond": ["noun group b", "warrior"],
	"mône": ["adjective", "smart, intelligent"],
	"môre": ["noun group a", "fox"],
	"môril": ["noun group b", "bowl"],
	"môrlas": ["adjective", "wrong"],
	"môrnan": ["verb", "to kiss passionately"],
	"môth": ["noun group c", "wraith"],
	"mûiral": ["noun group b", "armor, armour"],
	"mûr": ["noun group b", "basin, sink"],
	"mûrne": ["adjective", "hungry"],
	"mŷcûl": ["noun group c", "witch, hag"],
	"mŷl": ["noun group a", "gull, seagull"],
	"naben": ["verb", "to take, to get"],
	"nacen": ["verb", "to chop, to slice"],
	"nacir": ["noun group b", "throne"],
	"naese": ["noun group a", "leg"],
	"nagwa": ["noun group a", "scar"],
	"naiand": ["noun group b", "land, plain, moor; a wide land with little to no trees"],
	"naie": ["adverb", "here"],
	"nail": ["noun group a", "piece, part"],
	"naimash": ["verb", "to worry"],
	"nairande": ["noun group a", "ghost pipe (flower)"],
	"naiteshwe (1)": ["noun group a", "nostalgia, melancholy; yearning"],
	"naiteshwe (2)": ["adjective", "nostalgic, melancholic"],
	"naiti-bie": ["adjective/adverb", "true, right, correct"],
	"naitie": ["noun group a", "truth"],
	"naitien": ["verb", "to trust"],
	"nalash": ["verb", "to walk"],
	"naoca": ["noun group b", "rock, stone"],
	"naocaita": ["noun group b", "pickaxe"],
	"naore": ["noun group a", "rose (flower)"],
	"narash": ["verb", "to resist, to withstand, to endure, to bear (with or without \"vai\")"],
	"nare": ["noun group a", "dog, hound"],
	"nashre": ["noun group a", "grace, elegancy"],
	"nashres": ["adjective", "graceful, elegant"],
	"nasta": ["noun group b", "belt"],
	"naŋge": ["noun group a", "orange (food)"],
	"naŋyash": ["verb", "to shine, to gleam"],
	"nean ... min lûl": ["adjective", "alive"],
	"nean ... min mollie": ["adjective", "busy"],
	"nean": ["verb", "to be (verb group b)"],
	"nenda": ["noun group b", "bench"],
	"nezile": ["noun group b", "wall"],
	"neŋ": ["noun group a", "valley, mountain gorge"],
	"neŋtir": ["noun group b", "spellbook, tome, grimoire"],
	"nilzi": ["noun group c", "a scar caused by malice"],
	"ningse": ["noun group a", "goat"],
	"nirhala": ["noun group b", "whip"],
	"nisen": ["verb", "to tell someone, to say to someone"],
	"nith": ["noun group c", "a chilly ot unnerving feeling"],
	"niôr-nasse": ["noun group a", "servant"],
	"niôren": ["verb", "to serve, to work for"],
	"niôŋ": ["noun group a", "bee"],
	"niŋ": ["conjunction", "and"],
	"nobe": ["adjective", "half"],
	"nocor": ["noun group b", "lava, magma"],
	"nolla": ["noun group b", "urn"],
	"nolyash": ["verb", "to wish"],
	"nomas": ["noun group b", "boat"],
	"nossûiash": ["verb", "to come together, to gather up, to group together"],
	"nossûien": ["verb", "to gather, to collect"],
	"nôga": ["noun group c", "corpse, dead body"],
	"nôre": ["noun group a", "front"],
	"nûen": ["verb", "to make"],
	"nûin": ["noun group a", "pond"],
	"nûlie": ["noun group a", "flower petal"],
	"nûmala": ["noun group b", "library"],
	"nŷven": ["noun group b", "to chew"],
	"oldassi": ["noun group a", "plane of existence, dimension; world, realm"],
	"Oldumel": ["noun group a", "summer"],
	"ollash": ["verb", "to relax"],
	"olorda": ["noun group b", "fight, brawl, struggle"],
	"olûre": ["noun group a", "voice"],
	"omil": ["noun group a", "mushroom, toadstood, fungus"],
	"paed": ["noun group b", "word"],
	"pai": ["numeral", "two"],
	"paiash": ["verb", "to stop, to halt"],
	"paicu": ["adverb", "never"],
	"paiden": ["verb", "to shoot (with or without \"ci\")"],
	"paien": ["verb", "to stop something/someone; to block something"],
	"pala": ["noun group b", "trumpet"],
	"panen": ["verb", "to have"],
	"paon": ["adverb", "next"],
	"paon-aethe": ["noun group a", "tomorrow"],
	"pase": ["noun group a", "cat"],
	"pashen": ["verb", "to cut, to slash"],
	"pasiel": ["noun group a", "father"],
	"path": ["noun group b", "plate"],
	"paŋ": ["noun group b", "bow (weapon)"],
	"paŋge": ["noun group a", "clay"],
	"pelanôŋ": ["noun group b", "wine"],
	"pentren": ["verb", "to trespass, to walk into forbidden land"],
	"pentu": ["adverb", "first"],
	"pesse": ["noun group a", "skin"],
	"peŋ": ["noun group b", "tavern, restaurant"],
	"pin": ["noun group b", "insult"],
	"pinden": ["verb", "to taunt, to provoke; to mock"],
	"plaire": ["adjective/adverb", "rare, rarely"],
	"pleand": ["noun group b", "serving plate"],
	"possai": ["adverb", "many, much, a lot"],
	"pothe": ["noun group a", "head (anatomy)"],
	"pôlla": ["noun group b", "book"],
	"pôlômae": ["noun group a", "explosion"],
	"pôlômash": ["verb", "to explode"],
	"pônu": ["adverb", "forwards"],
	"pûllae": ["noun group a", "test, examination, assessment"],
	"pûllan": ["verb", "to test, to assess, to proof"],
	"pûmar": ["adjective", "rude, mean, impolite"],
	"pŷŋ": ["noun group a", "sprig, branchlet"],
	"qwa": ["noun group b", "coin"],
	"qwael": ["noun group a", "cave, cavern"],
	"qwael-bie": ["adjective", "undergound"],
	"qwaentan": ["verb", "to abandon"],
	"qwaithe": ["noun group a", "hide (animal skin)"],
	"qwalan": ["verb", "to read"],
	"qwande": ["noun group a", "fruit"],
	"qwantash": ["verb", "to run, to sprint"],
	"qwas": ["adjective", "purple"],
	"qwash": ["noun group b", "stew"],
	"qwasheme": ["noun group a", "pumpkin"],
	"qweldesh": ["verb", "to hide"],
	"qwelya-qwessie": ["noun group a", "high elf (d&d)"],
	"qwelyas": ["adjective", "great, magnificent"],
	"qwen": ["noun group b", "gold"],
	"qwerasir": ["noun group b", "kingdom, empire, nation"],
	"qwese": ["noun group a", "small river, stream"],
	"qwessa": ["noun group b", "pillow"],
	"qwessi-bie": ["adjective", "elvish, elven"],
	"qwessi-dae": ["noun group a", "an elven language, an elvish language"],
	"qwessie": ["noun group a", "elf"],
	"qweth": ["noun group b", "soup"],
	"qwevie": ["noun group a", "thoughts, mind"],
	"qwevien": ["verb", "to think"],
	"qwiresh": ["verb", "to rain"],
	"qwiressi": ["noun group a", "rainfall"],
	"qwolôrna": ["numeral", "million"],
	"qwossan": ["verb", "to remember"],
	"qwoŋbalas": ["adjective", "gorgeous"],
	"qwôl": ["noun group b", "dress, gown"],
	"qwôlar": ["noun group b", "hall, hallway"],
	"qwôra": ["noun group b", "chainmail, chain mail, maille"],
	"qwôren": ["verb", "to hug in a friendly way"],
	"qwŷl": ["noun group a", "ray, shaft, beam; a shaft of light from the sun or the moon"],
	"raelesh": ["verb", "to die, to succumb"],
	"raeleshtil": ["adjective", "dead"],
	"raien": ["verb", "to own, to have"],
	"raithen": ["verb", "to save, to rescue"],
	"ralwe": ["noun group a", "ghost, apparition, wisp, spirit, genie"],
	"Ranûdel": ["noun group a", "kingdom of ranudel"],
	"rassae": ["noun group a", "leaf"],
	"rassil": ["noun group a", "forest"],
	"rende": ["adjective", "sick, ill, infected"],
	"rendessul": ["noun group c", "sickness, illness, infection"],
	"ressie": ["adjective", "plant seed"],
	"reŋmie": ["noun group a", "breast (mammal); one of a woman's breasts"],
	"rielda": ["noun group b", "iron"],
	"rim": ["noun group a", "arm"],
	"rina": ["noun group b", "pouch, bag"],
	"rindalesh": ["verb", "to sing melodically"],
	"rindie": ["noun group a", "circle"],
	"roil": ["noun group c", "sludge, muck, decayed organic matter"],
	"ronathas": ["adjective", "great, mighty, powerful"],
	"rosse": ["noun group a", "window"],
	"rume": ["noun group a", "grass"],
	"rume-flowe": ["noun group a", "meadow, grassland, plains"],
	"rôcand": ["noun group c", "place of ruin, abandonment, or disaster; ancient ruin"],
	"rôl": ["noun group b", "mat, rug, carpet"],
	"rôn": ["noun group a", "mountain"],
	"rôn-beranae": ["noun group a", "mountain range"],
	"rûnas": ["adjective", "sweet, pleasant, nice, innocent"],
	"rûnathie": ["noun group a", "dream"],
	"rûndie": ["numeral", "nine"],
	"rŷŋ": ["noun group a", "something ancient, old, mystical, or magical"],
	"rŷŋ-gwandar": ["noun group a", "wizardry"],
	"s'-": ["prefix", "definite article shortened into prefix form, used with words that dont start with a vowel or s- (sh- words are the exception) (informal); examples: s'belde, s'shelesse, s'zanse"],
	"sa (1)": ["pronoun", "that (non-genitive)"],
	"sa (2)": ["article", "definite article"],
	"saelas": ["adjective", "black"],
	"saerash": ["verb", "to end, to finish"],
	"saerassi": ["noun group a", "ending, end"],
	"sailan": ["verb", "to enlighten"],
	"sailas": ["adjective", "wise"],
	"sailassi": ["noun group a", "wisdom"],
	"saldassi": ["noun group a", "lightning"],
	"samai": ["adverb", "enough"],
	"sanash": ["verb", "to will, to ought (future tense verb)"],
	"sanaŋ": ["noun group a", "lizard"],
	"sani": ["pronoun", "that (genitive)"],
	"saru": ["adverb", "last"],
	"sathas": ["adjective", "grey, gray"],
	"seiren": ["verb", "to play an instument"],
	"seldiren": ["verb", "to frighten, to cause fear, to cause dread"],
	"selesh": ["verb", "to transform, to become, to turn into (with or without \"ci\")"],
	"selo": ["numeral", "six"],
	"sentie": ["noun group a", "priest"],
	"serafalassi": ["noun group a", "butterfly"],
	"serenas": ["adjective", "cute, pretty"],
	"serenevathas": ["adjective", "beautiful, gorgeous"],
	"serie": ["noun group a", "girl"],
	"sesufele": ["noun group a", "description, appeareance"],
	"sevir": ["noun group a", "force, invisible force"],
	"shaelda": ["noun group b", "lever, switch"],
	"shan": ["noun group c", "pain"],
	"sheb": ["noun group b", "boot, shoe"],
	"shelai": ["adjective/adverb", "such, so; like this, that sort of, that kind of"],
	"shele": ["noun group a", "thing, object, something"],
	"shelesse": ["noun group a", "mist"],
	"shelŷnas": ["adjective", "delicious"],
	"shielde": ["noun group a", "tree"],
	"shone": ["noun group a", "knowledge"],
	"shraeŋ": ["noun group b", "illusion"],
	"shrilie": ["noun group a", "choir of birds"],
	"shrond": ["noun group b", "temple"],
	"shrunen": ["verb", "to buy"],
	"shrŷlwe": ["noun group a", "magical aura"],
	"shrŷna": ["noun group b", "hood, cowl"],
	"shrŷŋ": ["noun group b", "mirror"],
	"shwiŋ": ["noun group c", "bone"],
	"shôl": ["noun group b", "jewelry"],
	"shûlen": ["noun group b", "spoon"],
	"shŷne": ["noun group a", "thyme"],
	"sidir": ["noun group b", "pants, trousers"],
	"silitha": ["noun group b", "writing"],
	"silssien": ["verb", "to like, to favour"],
	"sin": ["pronoun", "this (non-genitive)"],
	"sincultir": ["noun group a", "black hellebore (flower)"],
	"sini": ["pronoun", "this (genitive)"],
	"siten": ["verb", "to grab"],
	"siôrash": ["verb", "to bathe"],
	"siôren": ["verb", "to wash"],
	"siŋga-lisse": ["noun group a", "saltwater brine"],
	"siŋgae": ["noun group a", "salt"],
	"slacash": ["verb", "to scream, to screech"],
	"slande": ["adjective", "weird, strange"],
	"slantha": ["noun group b", "chemise, frock, shift; a long, linen underdress"],
	"slend": ["noun group b", "an undergarment shirt/tunic, usually made of linen or cotton"],
	"sloren": ["verb", "to scare, to unnerve, to make tremble"],
	"slores": ["adjective", "unnerved, uncomfortable"],
	"slôssie": ["noun group a", "juice"],
	"solonde": ["noun group a", "tranquility, serenity, calmness"],
	"solsse": ["noun group a", "minute"],
	"sontan": ["verb", "to cook"],
	"spacul": ["noun group c", "ghost, specter, apparition, spirit"],
	"spaida": ["noun group b", "scabbard"],
	"spiencelen": ["verb", "to violate someone, to rape"],
	"spiŋgwe": ["noun group a", "fountain, geyser"],
	"spiŋgwesh": ["verb", "to gush, to rush, to shoot out"],
	"staelfe": ["noun group a", "tradition, custom"],
	"stûinde": ["noun group a", "animal, creature"],
	"suce": ["noun group a", "slime, ooze"],
	"swaesse": ["noun group a", "drink, beverage"],
	"swanze": ["noun group a", "sheep"],
	"swind": ["noun group b", "sign (for directions and text)"],
	"swintane": ["noun group a", "flute"],
	"swiŋye": ["noun group a", "type, kind, sort"],
	"sŷlae": ["noun group a", "swan"],
	"tacwel": ["noun group b", "hoe, cultivator, tiller"],
	"tael": ["noun group a", "god, deity"],
	"taend": ["noun group b", "a drum large enough that it's typically played whilst standing up"],
	"talaraŋ": ["noun group a", "sorcerer"],
	"taldaŋ": ["noun group a", "sorcery magic"],
	"tamalash": ["verb", "to shine brightly"],
	"tanda": ["noun group b", "bronze"],
	"tanten": ["verb", "to bake"],
	"tarien": ["noun group b", "gift, present"],
	"tassie": ["adjective", "crazy, mentally insane"],
	"tastassi": ["noun group a", "noticing, acknowledgement"],
	"tasten": ["verb", "to notice, to acknowledge"],
	"tayandôr": ["noun group a", "orchid (flower)"],
	"taŋcan": ["verb", "to must, to shall"],
	"tecse": ["noun group a", "sea shell, snail shell, clam shell"],
	"telde": ["noun group a", "wonder"],
	"teltan": ["verb", "to oath, to promise, to commit an oath, to make a promise"],
	"telyash": ["verb", "to stand up straight"],
	"tende": ["adjective", "tall, high"],
	"tendiswe": ["noun group a", "height"],
	"tenild": ["noun group b", "arm ring"],
	"terasse": ["noun group a", "lute"],
	"tesse": ["noun group a", "right"],
	"tessu": ["adverb", "rightwards"],
	"teŋgen": ["verb", "to arrive at, to reach, to get to"],
	"teŋgesh": ["verb", "to come"],
	"teŋnen": ["verb", "to hear"],
	"thael": ["noun group a", "clothing, apparel"],
	"thaiden": ["verb", "to stretch, to lengthen; to draw a bow"],
	"thaine": ["noun group a", "law, rules"],
	"thaisse": ["noun group a", "cloud, billow"],
	"thalashaŋ": ["noun group a", "druidry magic"],
	"thalassi": ["noun group a", "air"],
	"thas": ["numeral", "five"],
	"thash": ["verb", "to start, to begin"],
	"thelen": ["verb", "to find, to look for"],
	"there": ["adjective", "long"],
	"theren": ["adverb", "for a long time"],
	"theressi": ["noun group a", "length"],
	"thewan": ["verb", "to sew (with or without \"gai\" or \"mi\")"],
	"thiemen hassu": ["verb", "to hold someone's hand, to lead someone by hand (with \"mi\" + who)"],
	"thiemen": ["verb", "to lead, to guide"],
	"thienas": ["numeral", "ten"],
	"thilde": ["noun group a", "ally, teammate"],
	"thilende": ["noun group a", "game, sport"],
	"thilu": ["adverb", "far"],
	"thime": ["noun group a", "silk"],
	"thiva": ["noun group b", "shears, scissors"],
	"thobae": ["noun group a", "finger"],
	"thomash": ["verb", "to want"],
	"thore": ["noun group a", "a loud, thunderous sound"],
	"thrande": ["noun group a", "orchard, garden"],
	"throssen": ["verb", "to suck"],
	"thrûvi": ["noun group b", "hay, thatch, dry grass"],
	"thrŷl": ["noun group b", "finger ring"],
	"thuŋ": ["noun group c", "fear, terror"],
	"thuŋnen": ["verb", "to terrorise, to cause terror"],
	"thwossiesh": ["verb", "to would"],
	"thûca": ["numeral", "hundred"],
	"thûicen": ["verb", "to mean something"],
	"thûrda": ["noun group b", "polearm (weapon)"],
	"thûvala": ["noun group b", "spear"],
	"thŷlen": ["verb", "to taste"],
	"tilie": ["noun group a", "oath, promise"],
	"tima": ["noun group b", "symbol, glyph"],
	"tiren": ["verb", "to close"],
	"tith": ["noun group b", "tower"],
	"tiôr": ["noun group b", "dwarf"],
	"trew": ["noun group a", "edelweiss (flower)"],
	"tulde": ["adjective", "lost, missing, gone"],
	"twaisen": ["verb", "to guess, to assume, to suppose"],
	"twaraŋ": ["noun group a", "thunder"],
	"twasa": ["numeral", "three"],
	"tônd": ["noun group b", "cauldron, pot"],
	"tûin": ["noun group a", "island"],
	"tûlen": ["verb", "to bind, to fixate (with or without \"min\")"],
	"tûlla": ["noun group b", "blanket, bed cover"],
	"tûmen": ["verb", "to hit, to strike"],
	"tûnesh": ["verb", "to wonder (with or without \"ci\")"],
	"tûssil": ["noun group a", "moon"],
	"tûssil-glasse": ["noun group a", "moonlight"],
	"tûssil-qwessie": ["noun group a", "moon elf"],
	"tŷlai": ["noun group a", "music"],
	"ulsela": ["noun group b", "glave, halberd, atgeir"],
	"ulumai ci": ["preposition", "used for"],
	"ulumai": ["preposition", "using with, prepared with"],
	"ulumai-lindu": ["adverb", "in return"],
	"umash": ["verb", "to wait (with \"am\" + verb, object, or time)"],
	"ussas": ["adjective", "tired, exhausted"],
	"vace": ["verb", "to stab"],
	"vaere": ["noun group a", "fern"],
	"vai": ["preposition", "from"],
	"vana": ["noun group b", "mercenary"],
	"vancie": ["noun group a", "oak"],
	"vand": ["noun group b", "staff, stave"],
	"vaondre": ["noun group a", "pine"],
	"vassash": ["verb", "to laugh"],
	"vasten": ["verb", "to rip, to tear"],
	"vayu": ["adverb", "away"],
	"velie": ["noun group a", "event, activity, gathering"],
	"velôma": ["noun group b", "parchment"],
	"veriŋnesh": ["verb", "to leave, to depart"],
	"ves": ["adjective", "some"],
	"vessi": ["noun group a", "place, location"],
	"viald": ["noun group b", "a sword that is noble, ceremonial, or of extremely high status"],
	"viel": ["noun group a", "cause, origin, beginning"],
	"vil": ["noun group b", "metal"],
	"vim": ["conjunction", "which, who, whom, like, such as (not a question word)"],
	"vis": ["adverb", "yes"],
	"visses": ["adjective", "sharp"],
	"viôrda": ["noun group b", "cemetary"],
	"vlenten": ["verb", "to fling, to throw, to sling"],
	"vlussi": ["noun group a", "flower, bloom"],
	"vlûrash": ["verb", "to flow"],
	"vonen": ["verb", "to protect, to ward, to guard"],
	"vossae": ["noun group a", "brother"],
	"vucen": ["verb", "to use"],
	"vulsse": ["noun group a", "wolf"],
	"vôma": ["conjunction", "who, which"],
	"vônu": ["adverb", "near"],
	"vŷla": ["noun group b", "city"],
	"waelash": ["verb", "to wander astray"],
	"waelashtil": ["adjective", "lost, alone, wandered off"],
	"waelfe": ["noun group a", "south"],
	"waide": ["noun group a", "linen"],
	"waiŋnen": ["noun group b", "to sway, to swing"],
	"wamesh": ["verb", "to emit a smell, to smell like (with or without \"ci\")"],
	"waren": ["verb", "to boil something"],
	"waresh": ["verb", "to boil"],
	"wasen": ["verb", "to surprise"],
	"weithi-nasse": ["noun group a", "explorer"],
	"weithie": ["noun group a", "exploration, roam"],
	"weithien": ["verb", "to explore, to roam around"],
	"weles": ["adjective", "yellow"],
	"welfu": ["adverb", "southward"],
	"wenwarie": ["noun group a", "camaraderie, chemistry (relationships)"],
	"wilyen": ["verb", "to envy, to wish to be like"],
	"wilyessi": ["noun group a", "envy"],
	"wilyiswe": ["noun group a", "enviousness"],
	"winde-yeldie": ["noun group a", "wedding"],
	"windesh": ["verb", "to marry with, to wed (with \"min\")"],
	"windessi": ["verb", "marriage, wedlock"],
	"wiôlen": ["verb", "to burn, to set fire to; to scorch, to flame, to burn"],
	"wiôlesh": ["verb", "to burn"],
	"wond": ["noun group b", "haze"],
	"wune": ["adjective", "good"],
	"wôr": ["noun group a", "wind"],
	"yaer": ["noun group a", "bear"],
	"yaldar": ["noun group a", "giant, jotun, ettin"],
	"yalssi": ["noun group a", "violin, vielle, viola"],
	"yandas": ["adjective", "sweet (taste)"],
	"yasen": ["verb", "to join"],
	"yaŋgstarssa": ["noun group b", "portal"],
	"yaŋu": ["adverb", "across"],
	"yearen": ["verb", "to know"],
	"yeldie": ["noun group a", "festival"],
	"yelesh": ["verb", "to sing quietly"],
	"yelesiel": ["noun group a", "mother"],
	"yelon": ["noun group a", "thigh"],
	"yendrae": ["noun group a", "harp"],
	"yene": ["adjective", "young"],
	"yenessi": ["noun group a", "cattle, cow, yak"],
	"yethi-nasse": ["noun group a", "spy (someone who spies)"],
	"yethien": ["verb", "to spy, to watch discreetly, to follow and watch without them knowing; to watch from the trees or roof"],
	"yome": ["adjective", "soft"],
	"yumu": ["adverb", "maybe, might, probably, could"],
	"yune": ["noun group a", "garden, yard"],
	"yôl": ["noun group a", "lock of hair"],
	"yômash": ["verb", "to groan, to moan"],
	"yûlae": ["noun group a", "power, might"],
	"zaelash": ["verb", "to grow"],
	"zaelen": ["verb", "to grow something"],
	"zaer": ["noun group b", "accident"],
	"zaerai": ["adverb", "accidentally"],
	"zaesh": ["noun group b", "house, home"],
	"zaeshe": ["noun group a", "home"],
	"zaevai": ["adverb", "accidentally"],
	"zaias": ["adjective", "white"],
	"zaimse": ["noun group a", "ash"],
	"zaitash": ["noun group c", "criminal, prisoner"],
	"zaiwen": ["verb", "to should, to ought"],
	"zalûdiem": ["noun group a", "angel, celestial"],
	"zane": ["noun group a", "neck"],
	"zanse": ["noun group a", "ice"],
	"zaranil": ["noun group a", "weather"],
	"zasha": ["noun group b", "knife, dagger"],
	"zath": ["noun group b", "fool"],
	"zath-bie": ["adjective", "foolish, naive, unaware"],
	"zeile": ["noun group a", "insect"],
	"zelesh": ["verb", "to fall down"],
	"zemiel": ["noun group a", "emerald"],
	"zene": ["noun group a", "smile"],
	"zenesh": ["verb", "to smile"],
	"zerûla": ["noun group b", "merchant, seller, clerk"],
	"zerûla-felde": ["noun group a", "markets, fair, festival"],
	"zesûind": ["noun group b", "shop, store"],
	"ziena": ["noun group b", "necklace"],
	"zilen": ["verb", "to allow, to let; to set free"],
	"zirfai": ["verb", "divination; seidr, seiðr, seidur"],
	"zisses": ["adjective", "free"],
	"ziŋyash": ["verb", "to glimmer, to shimmer, to glow"],
	"zlaemash": ["verb", "to blush, to fluster, to redden in the face"],
	"zlonden": ["verb", "to love passionately"],
	"zlondessi": ["noun group a", "romantic love"],
	"zlondiswe": ["noun group a", "romantic allure, sexual desire; allure, appeal, attractiveness"],
	"zolla": ["noun group b", "a gemstone embedded into metal"],
	"zonde": ["noun group a", "strait, channel (a landform where two seperate landmasses are almost touching but is seperated by deep water)"],
	"zôlsil": ["noun group c", "damage"],
	"zôril": ["noun group a", "sanctuary, church, temple, mosque"],
	"zôrnel": ["noun group b", "crucible steel"],
	"zûinu": ["adverb", "through"],
	"zûlas": ["adjective", "visible"],
	"zûren": ["verb", "to draw"],
	"zŷl": ["noun group a", "drop of liquid"],
	"ôb": ["numeral", "one"],
	"ôces": ["preposition", "except"],
	"ôlaish": ["verb", "to sleep"],
	"ôlathvial": ["noun group b", "cloak, mantle"],
	"ôle": ["noun group a", "peace, calm, stillness"],
	"ôlir": ["noun group b", "smoke"],
	"ôlse": ["adjective", "deep"],
	"ôrbin": ["noun group c", "spider"],
	"ôrshen": ["verb", "to sadden, to depress"],
	"ôrshent i ere": ["phrase", "means \"im sorry\""],
	"ôrshentele": ["adjective", "sad, unhappy, let down (because of something)"],
	"ôrshes": ["adjective", "sad, unhappy"],
	"ôrshessi": ["noun group a", "sadness, sorrow"],
	"ôsa": ["noun group b", "rope"],
	"ôte": ["noun group a", "dirt, earth, soil"],
	"ûcanan": ["verb", "to choke someone"],
	"ûcanash": ["verb", "to choke on"],
	"ûga": ["noun group c", "ogre"],
	"ûllanor": ["noun group c", "sorrow, grief, heartache, heartbreak"],
	"ûne": ["adjective/adverb", "all"],
	"ûrci": ["noun group c", "orc, ork"],
	"ûthe": ["noun group a", "emotion, feelings"],
	"ŷcil": ["noun group c", "snake"],
	"ŷla": ["noun group b", "alchoholic drink"],
	"ŷndes": ["adjective", "viscous, glutinous, sticky (like honey)"],
	"ŷndûl": ["noun group c", "bomb, explosive"],
	"ŷre": ["noun group a", "star"],
	"ŷrŋ": ["noun group a", "bell"],
};

const special_declensions = {};
